<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * AccountSubaccountsSwitchPlans endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: AccountSubaccountsSwitchPlans
 *
 * @see docs/smart/resources/AccountSubaccountsSwitchPlans.md
 */
class AccountSubaccountsSwitchPlans extends AbstractResource
{
    /**
     * Employees/AccountSubaccountsSwitchPlans/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/subaccount_switch_plans
     * OAuth scopes: user, employee
     *
     * Body fields ($body, JSON):
     *   - target_subaccount_uuid (string) required
     *   - source_subaccount_uuid (string) required
     *   - switch_type (string)
     *   - amount (mixed)
     *   - age (integer)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createSubaccountSwitchPlan(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/subaccount_switch_plans', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Employees/AccountSubaccountsSwitchPlans/Confirm
     *
     * POST /companies/{company_id}/employees/{employee_id}/subaccount_switch_plans/{id}/confirm
     * OAuth scopes: user, employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function confirmSubaccountSwitchPlan(string|int $companyId, string|int $employeeId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/subaccount_switch_plans/{id}/confirm', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
