<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * AccountClaiming endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Account-Claiming
 *
 * @see docs/smart/resources/AccountClaiming.md
 */
class AccountClaiming extends AbstractResource
{
    /**
     * Account-Claiming/Attempt
     *
     * POST /account-claiming/attempts
     * Authentication: none required
     *
     * Body fields ($body, JSON):
     *   - first_name (string)
     *   - last_name (string)
     *   - date_of_birth (string)
     *   - national_insurance_number (string)
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createAttempt(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/account-claiming/attempts', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * Account-Claiming/Attempt
     *
     * GET /account-claiming/attempts/{uuid}/
     * Authentication: none required
     * Host: account-claiming service
     *
     * @param string|int $uuid uuid path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getAttempt(string|int $uuid, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/account-claiming/attempts/{uuid}/', ['uuid' => $uuid], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
            'service' => 'account-claiming',
        ]);
    }

    /**
     * Account-Claiming/Attempt/AdditionalData
     *
     * PATCH /account-claiming/attempts/{uuid}/additional-data
     * Authentication: none required
     *
     * Body fields ($body, JSON):
     *   - previous_email (string)
     *   - phone_number (string)
     *   - address_line_1 (string)
     *   - address_line_2 (string, nullable)
     *   - address_line_3 (string, nullable)
     *   - city (string)
     *   - country (string)
     *   - postcode (string)
     *
     * @param string|int $uuid uuid path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateAttemptAdditionalData(string|int $uuid, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/account-claiming/attempts/{uuid}/additional-data', ['uuid' => $uuid], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * Account-Claiming/Attempt/Email
     *
     * PATCH /account-claiming/attempts/{uuid}/email
     * Authentication: none required
     *
     * Body fields ($body, JSON):
     *   - current_email (string)
     *
     * @param string|int $uuid uuid path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateAttemptEmail(string|int $uuid, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/account-claiming/attempts/{uuid}/email', ['uuid' => $uuid], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * Account-Claiming/Attempt/Password
     *
     * PATCH /account-claiming/attempts/{uuid}/password
     * Authentication: none required
     *
     * Body fields ($body, JSON):
     *   - password (string)
     *   - password_confirmation (string)
     *
     * @param string|int $uuid uuid path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateAttemptPassword(string|int $uuid, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/account-claiming/attempts/{uuid}/password', ['uuid' => $uuid], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * Account-Claiming/confirm-personal-data
     *
     * POST /account-claiming/confirm-personal-data
     * OAuth scopes: any valid token
     * Host: account-claiming service
     *
     * Body fields ($body, JSON):
     *   - title (string, nullable)
     *   - first_name (string, nullable)
     *   - middle_name (string, nullable)
     *   - last_name (string, nullable)
     *   - phone_number (string, nullable)
     *   - address_line_1 (string, nullable)
     *   - address_line_2 (string, nullable)
     *   - address_line_3 (string, nullable)
     *   - city (string, nullable)
     *   - country (string, nullable)
     *   - postcode (string, nullable)
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function confirmPersonalData(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/account-claiming/confirm-personal-data', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
            'service' => 'account-claiming',
        ]);
    }

    /**
     * Account-Claiming/current-attempt
     *
     * GET /account-claiming/current-attempt
     * OAuth scopes: any valid token
     * Host: account-claiming service
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getCurrentAttempt(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/account-claiming/current-attempt', [], [
            'query' => $query,
            'headers' => $headers,
            'service' => 'account-claiming',
        ]);
    }

    /**
     * Account-Claiming/Password-Validations
     *
     * GET /account-claiming/password-validations
     * Authentication: none required
     * Host: account-claiming service
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getPasswordValidations(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/account-claiming/password-validations', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
            'service' => 'account-claiming',
        ]);
    }
}
