<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * AdditionalTaxResidences endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: AdditionalTaxResidences
 *
 * @see docs/smart/resources/AdditionalTaxResidences.md
 */
class AdditionalTaxResidences extends AbstractResource
{
    /**
     * Companies/AdditionalTaxResidences/List
     *
     * GET /companies/{company_id}/employees/{employee_id}/additional_tax_residences
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - offset (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listAdditionalTaxResidences(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/additional_tax_residences', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/AdditionalTaxResidences/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/additional_tax_residences
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - country (string) required
     *   - tax_reference_number (string) required
     *   - tax_reference_type (string) required
     *
     * Headers ($headers):
     *   - Accept-Language
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createAdditionalTaxResidence(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/additional_tax_residences', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/AdditionalTaxResidences/Update
     *
     * PUT /companies/{company_id}/employees/{employee_id}/additional_tax_residences/{id}
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - country (string) required
     *   - tax_reference_number (string) required
     *   - tax_reference_type (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceAdditionalTaxResidence(string|int $companyId, string|int $employeeId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/employees/{employee_id}/additional_tax_residences/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/AdditionalTaxResidences/Update
     *
     * PATCH /companies/{company_id}/employees/{employee_id}/additional_tax_residences/{id}
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - country (string) required
     *   - tax_reference_number (string) required
     *   - tax_reference_type (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateAdditionalTaxResidence(string|int $companyId, string|int $employeeId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{employee_id}/additional_tax_residences/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/AdditionalTaxResidences/Destroy
     *
     * DELETE /companies/{company_id}/employees/{employee_id}/additional_tax_residences/{id}
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deleteAdditionalTaxResidence(string|int $companyId, string|int $employeeId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/companies/{company_id}/employees/{employee_id}/additional_tax_residences/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
