<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * AdviserInvitations endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: AdviserInvitations
 *
 * @see docs/smart/resources/AdviserInvitations.md
 */
class AdviserInvitations extends AbstractResource
{
    /**
     * Companies/AdviserInvitations/List
     *
     * GET /companies/{company_id}/adviser_invitations
     * OAuth scopes: customer
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object)
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listAdviserInvitations(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/adviser_invitations', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/AdviserInvitations/Create
     *
     * POST /companies/{company_id}/adviser_invitations
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - adviser_email (string)
     *   - role (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createAdviserInvitation(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/adviser_invitations', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/AdviserInvitations/Cancel
     *
     * POST /companies/{company_id}/adviser_invitations/{id}/cancel
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function cancelAdviserInvitation(string|int $companyId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/adviser_invitations/{id}/cancel', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
