<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * AdviserCompanies endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: AdviserCompanies
 *
 * @see docs/smart/resources/AdviserCompanies.md
 */
class AdviserCompanies extends AbstractResource
{
    /**
     * AdviserCompany/Create
     *
     * POST /adviser_companies
     * OAuth scopes: user
     *
     * Body fields ($body, JSON):
     *   - adviser_company (object)
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createAdviserCompany(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/adviser_companies', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * AdviserCompanies/Update
     *
     * PATCH /adviser_companies/adviser/{adviser_id}/company/{company_id}
     * OAuth scopes: user
     *
     * Body fields ($body, JSON):
     *   - adviser_company (object)
     *
     * @param string|int $adviserId adviser_id path parameter
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateAdviserCompany(string|int $adviserId, string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/adviser_companies/adviser/{adviser_id}/company/{company_id}', ['adviser_id' => $adviserId, 'company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
