<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * AdviserExports endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: AdviserExports
 *
 * @see docs/smart/resources/AdviserExports.md
 */
class AdviserExports extends AbstractResource
{
    /**
     * Advisers/Exports/Get
     *
     * GET /advisers/{adviser_id}/exports/{id}
     * OAuth scopes: user
     *
     * @param string|int $adviserId adviser_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getExport(string|int $adviserId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/advisers/{adviser_id}/exports/{id}', ['adviser_id' => $adviserId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
