<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Advisers endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Adviser
 *
 * @see docs/smart/resources/Advisers.md
 */
class Advisers extends AbstractResource
{
    /**
     * Advisers/List
     *
     * GET /advisers
     * OAuth scopes: customer
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: id, name, address
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listAdvisers(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/advisers', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Advisers/Create
     *
     * POST /advisers
     * Authentication: none required
     *
     * Body fields ($body, JSON):
     *   - logo (file)
     *   - name (string) required
     *   - address (string) required
     *   - signup_start (string)
     *   - signup_finish (string)
     *   - channel (string)
     *   - agent_number (string)
     *   - broker_role (string)
     *   - broker_channel (string)
     *   - annuity_option_enabled (boolean)
     *   - marketing_included (boolean)
     *   - email (string) required
     *   - password (string) required
     *   - title (string)
     *   - forename (string) required
     *   - surname (string) required
     *   - telephone (string) required
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createAdviser(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/advisers', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * Advisers/GetByToken
     *
     * GET /advisers/by_token
     * Authentication: none required
     *
     * Query parameters ($query):
     *   - referralToken (string) required
     *   - include[] (mixed[]): Items one of: `shortcut`
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getAdviserByToken(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/advisers/by_token', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * Advisers/Get
     *
     * GET /advisers/{id}
     * OAuth scopes: user
     *
     * Query parameters ($query):
     *   - include[] (mixed[]): Items one of: `shortcut`
     *
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getAdviser(string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/advisers/{id}', ['id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Advisers/Update
     *
     * PUT /advisers/{id}
     * OAuth scopes: user
     *
     * Body fields ($body, JSON):
     *   - logo (file)
     *   - name (string)
     *   - address (string)
     *   - signup_start (string)
     *   - signup_finish (string)
     *   - channel (string)
     *   - agent_number (string)
     *   - broker_role (string)
     *   - broker_channel (string)
     *   - annuity_option_enabled (boolean)
     *
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceAdviser(string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/advisers/{id}', ['id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Advisers/Update
     *
     * PATCH /advisers/{id}
     * OAuth scopes: user
     *
     * Body fields ($body, JSON):
     *   - logo (file)
     *   - name (string)
     *   - address (string)
     *   - signup_start (string)
     *   - signup_finish (string)
     *   - channel (string)
     *   - agent_number (string)
     *   - broker_role (string)
     *   - broker_channel (string)
     *   - annuity_option_enabled (boolean)
     *
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateAdviser(string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/advisers/{id}', ['id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Advisers/ManagedEmployees
     *
     * POST /advisers/{id}/managed-employees
     * OAuth scopes: user
     *
     * Body fields ($body, JSON):
     *   - employee_id (integer)
     *
     * @param string|int $id Adviser ID
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listManagedEmployees(string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/advisers/{id}/managed-employees', ['id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
