<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * AvailableWithdrawalOptions endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: AvailableWithdrawalOptions
 *
 * @see docs/smart/resources/AvailableWithdrawalOptions.md
 */
class AvailableWithdrawalOptions extends AbstractResource
{
    /**
     * AvailableWithdrawalOptions/List
     *
     * GET /companies/{company_id}/employees/{employee_id}/available_withdrawal_options
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - target_retirement_year (integer): Target retirement year to filter funds
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listAvailableWithdrawalOptions(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/available_withdrawal_options', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
