<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * BankAccountDetails endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: BankAccountDetails, BankAccountDetail
 *
 * @see docs/smart/resources/BankAccountDetails.md
 */
class BankAccountDetails extends AbstractResource
{
    /**
     * Companies/BankAccountDetails/List
     *
     * GET /companies/{company_id}/bank_account_details
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listBankAccountDetails(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/bank_account_details', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/BankAccountDetails/Create
     *
     * POST /companies/{company_id}/bank_account_details
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - bank_account_detail (object)
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createCompanyBankAccountDetail(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/bank_account_details', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/BankAccountDetails/Managable
     *
     * GET /companies/{company_id}/bank_account_details/managable
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listManageableBankAccountDetails(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/bank_account_details/managable', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/BankAccountDetails/SensitiveData
     *
     * GET /companies/{company_id}/bank_account_details/{bank_account_detail_id}/sensitive_data
     * OAuth scopes: customer
     *
     * Query parameters ($query):
     *   - field_names[] (string[]) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $bankAccountDetailId bank_account_detail_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getBankAccountDetailSensitiveData(string|int $companyId, string|int $bankAccountDetailId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/bank_account_details/{bank_account_detail_id}/sensitive_data', ['company_id' => $companyId, 'bank_account_detail_id' => $bankAccountDetailId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/BankAccountDetails/List
     *
     * GET /companies/{company_id}/bank_account_details/{id}
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getCompanyBankAccountDetail(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/bank_account_details/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/BankAccountDetails/Update
     *
     * PUT /companies/{company_id}/bank_account_details/{id}
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - account_name (string)
     *   - bank_name (string)
     *   - country_code (string)
     *   - account_number (string)
     *   - account_number_format (string)
     *   - reviewed (boolean)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceCompanyBankAccountDetail(string|int $companyId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/bank_account_details/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/BankAccountDetails/Update
     *
     * PATCH /companies/{company_id}/bank_account_details/{id}
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - account_name (string)
     *   - bank_name (string)
     *   - country_code (string)
     *   - account_number (string)
     *   - account_number_format (string)
     *   - reviewed (boolean)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateCompanyBankAccountDetail(string|int $companyId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/bank_account_details/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/BankAccountDetails/Destroy
     *
     * DELETE /companies/{company_id}/bank_account_details/{id}
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deleteBankAccountDetail(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/companies/{company_id}/bank_account_details/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Employees/BankAccountDetail/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/bank_account_detail
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getEmployeeBankAccountDetail(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/bank_account_detail', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Employees/BankAccountDetail/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/bank_account_detail
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - bank_account_detail (object)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createEmployeeBankAccountDetail(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/bank_account_detail', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Employees/BankAccountDetail/Update
     *
     * PUT /companies/{company_id}/employees/{employee_id}/bank_account_detail
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - account_name (string)
     *   - bank_name (string)
     *   - country_code (string)
     *   - account_number (string)
     *   - account_number_format (string)
     *   - reviewed (boolean)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceEmployeeBankAccountDetail(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/employees/{employee_id}/bank_account_detail', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Employees/BankAccountDetail/Update
     *
     * PATCH /companies/{company_id}/employees/{employee_id}/bank_account_detail
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - account_name (string)
     *   - bank_name (string)
     *   - country_code (string)
     *   - account_number (string)
     *   - account_number_format (string)
     *   - reviewed (boolean)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateEmployeeBankAccountDetail(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{employee_id}/bank_account_detail', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Employees/BankAccountDetail/Validate
     *
     * POST /companies/{company_id}/employees/{employee_id}/bank_account_detail/validate
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - bank_account_detail (object)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function validateBankAccountDetail(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/bank_account_detail/validate', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
