<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * BenefitCheckResults endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: BenefitCheckResults
 *
 * @see docs/smart/resources/BenefitCheckResults.md
 */
class BenefitCheckResults extends AbstractResource
{
    /**
     * BenefitCheckResults/Update
     *
     * Should to be used when the employee / user finishes Shufti Pro (KYC) journey and gets redirected
     * back to Smart Platform.
     *
     * PUT /companies/{company_id}/employees/{employee_id}/benefits/{benefit_id}/benefit_check_results/{id}
     * OAuth scopes: user, customer
     *
     * Headers ($headers):
     *   - signature required: Signature captured from third-party service that is used to verify the authenticity of user return back event.
     *
     * @param string|int $companyId ID of a company
     * @param string|int $employeeId ID of an employee
     * @param string|int $benefitId ID of a benefit check result
     * @param string|int $id ID of a benefit check result
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceBenefitCheckResult(string|int $companyId, string|int $employeeId, string|int $benefitId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/employees/{employee_id}/benefits/{benefit_id}/benefit_check_results/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'benefit_id' => $benefitId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * BenefitCheckResults/Update
     *
     * Should to be used when the employee / user finishes Shufti Pro (KYC) journey and gets redirected
     * back to Smart Platform.
     *
     * PATCH /companies/{company_id}/employees/{employee_id}/benefits/{benefit_id}/benefit_check_results/{id}
     * OAuth scopes: user, customer
     *
     * Headers ($headers):
     *   - signature required: Signature captured from third-party service that is used to verify the authenticity of user return back event.
     *
     * @param string|int $companyId ID of a company
     * @param string|int $employeeId ID of an employee
     * @param string|int $benefitId ID of a benefit check result
     * @param string|int $id ID of a benefit check result
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateBenefitCheckResult(string|int $companyId, string|int $employeeId, string|int $benefitId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{employee_id}/benefits/{benefit_id}/benefit_check_results/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'benefit_id' => $benefitId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * BenefitCheckResults/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/benefits/{id}/benefit_check_results
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listBenefitCheckResults(string|int $companyId, string|int $employeeId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/benefits/{id}/benefit_check_results', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
