<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * BenefitForms endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: BenefitForm
 *
 * @see docs/smart/resources/BenefitForms.md
 */
class BenefitForms extends AbstractResource
{
    /**
     * BenefitForms/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/benefit_categories/{benefit_category_id}/benefit_form
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - requested_benefit_amount (number)
     *   - regular_income_amount (number)
     *   - regular_income_end_age (integer)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $benefitCategoryId benefit_category_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createBenefitForm(string|int $companyId, string|int $employeeId, string|int $benefitCategoryId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/benefit_categories/{benefit_category_id}/benefit_form', ['company_id' => $companyId, 'employee_id' => $employeeId, 'benefit_category_id' => $benefitCategoryId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * BenefitForms/Update
     *
     * PUT /companies/{company_id}/employees/{employee_id}/benefit_categories/{benefit_category_id}/benefit_form
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - requested_benefit_amount (number)
     *   - regular_income_amount (number)
     *   - regular_income_end_age (integer)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $benefitCategoryId benefit_category_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceBenefitForm(string|int $companyId, string|int $employeeId, string|int $benefitCategoryId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/employees/{employee_id}/benefit_categories/{benefit_category_id}/benefit_form', ['company_id' => $companyId, 'employee_id' => $employeeId, 'benefit_category_id' => $benefitCategoryId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * BenefitForms/Update
     *
     * PATCH /companies/{company_id}/employees/{employee_id}/benefit_categories/{benefit_category_id}/benefit_form
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - requested_benefit_amount (number)
     *   - regular_income_amount (number)
     *   - regular_income_end_age (integer)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $benefitCategoryId benefit_category_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateBenefitForm(string|int $companyId, string|int $employeeId, string|int $benefitCategoryId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{employee_id}/benefit_categories/{benefit_category_id}/benefit_form', ['company_id' => $companyId, 'employee_id' => $employeeId, 'benefit_category_id' => $benefitCategoryId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * BenefitForms/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/benefit_form
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getBenefitForm(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/benefit_form', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * BenefitEvidenceUploads/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/benefit_form/benefit_evidence_uploads
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listBenefitEvidenceUploads(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/benefit_form/benefit_evidence_uploads', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * BenefitEvidenceUploads/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/benefit_form/benefit_evidence_uploads
     * OAuth scopes: employee
     *
     * Body fields ($body, multipart/form-data):
     *   - id (integer)
     *   - benefit_evidence_type_id (integer) required
     *   - state (string)
     *   - comment (string)
     *   - preupload_url (string)
     *   - expires_on (string)
     *   - file (file)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body multipart fields; files as fopen() resources or ['contents' => ..., 'filename' => ...]
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createBenefitEvidenceUpload(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/benefit_form/benefit_evidence_uploads', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'multipart' => $body,
        ]);
    }

    /**
     * BenefitEvidenceUploads/ConfirmAll
     *
     * PATCH /companies/{company_id}/employees/{employee_id}/benefit_form/benefit_evidence_uploads/confirm_all
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function confirmAllBenefitEvidenceUploads(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{employee_id}/benefit_form/benefit_evidence_uploads/confirm_all', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * BenefitEvidenceUploads/Update
     *
     * PUT /companies/{company_id}/employees/{employee_id}/benefit_form/benefit_evidence_uploads/{benefit_evidence_upload_id}
     * OAuth scopes: employee
     *
     * Body fields ($body, multipart/form-data):
     *   - file (file) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $benefitEvidenceUploadId benefit_evidence_upload_id path parameter
     * @param array $body multipart fields; files as fopen() resources or ['contents' => ..., 'filename' => ...]
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceBenefitEvidenceUpload(string|int $companyId, string|int $employeeId, string|int $benefitEvidenceUploadId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/employees/{employee_id}/benefit_form/benefit_evidence_uploads/{benefit_evidence_upload_id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'benefit_evidence_upload_id' => $benefitEvidenceUploadId], [
            'query' => $query,
            'headers' => $headers,
            'multipart' => $body,
        ]);
    }

    /**
     * BenefitEvidenceUploads/Update
     *
     * PATCH /companies/{company_id}/employees/{employee_id}/benefit_form/benefit_evidence_uploads/{benefit_evidence_upload_id}
     * OAuth scopes: employee
     *
     * Body fields ($body, multipart/form-data):
     *   - file (file) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $benefitEvidenceUploadId benefit_evidence_upload_id path parameter
     * @param array $body multipart fields; files as fopen() resources or ['contents' => ..., 'filename' => ...]
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateBenefitEvidenceUpload(string|int $companyId, string|int $employeeId, string|int $benefitEvidenceUploadId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{employee_id}/benefit_form/benefit_evidence_uploads/{benefit_evidence_upload_id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'benefit_evidence_upload_id' => $benefitEvidenceUploadId], [
            'query' => $query,
            'headers' => $headers,
            'multipart' => $body,
        ]);
    }

    /**
     * BenefitEvidenceUploads/Destroy
     *
     * DELETE /companies/{company_id}/employees/{employee_id}/benefit_form/benefit_evidence_uploads/{benefit_evidence_upload_id}
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $benefitEvidenceUploadId benefit_evidence_upload_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deleteBenefitEvidenceUpload(string|int $companyId, string|int $employeeId, string|int $benefitEvidenceUploadId, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/companies/{company_id}/employees/{employee_id}/benefit_form/benefit_evidence_uploads/{benefit_evidence_upload_id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'benefit_evidence_upload_id' => $benefitEvidenceUploadId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * BenefitQuestionResponses/Update
     *
     * PATCH /companies/{company_id}/employees/{employee_id}/benefit_form/benefit_question_responses/
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateBenefitQuestionResponses(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{employee_id}/benefit_form/benefit_question_responses/', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * BenefitForms/Cancel
     *
     * POST /companies/{company_id}/employees/{employee_id}/benefit_form/cancel
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function cancelBenefitForm(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/benefit_form/cancel', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * BenefitForms/Submit
     *
     * POST /companies/{company_id}/employees/{employee_id}/benefit_form/submit
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function submitBenefitForm(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/benefit_form/submit', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * BenefitForms/VerificationUrl
     *
     * GET /companies/{company_id}/employees/{employee_id}/benefit_form/verification_url
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getBenefitFormVerificationUrl(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/benefit_form/verification_url', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * BenefitForms/GenerateVerificationUrl
     *
     * POST /companies/{company_id}/employees/{employee_id}/benefit_form/verification_url
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - redirect_url (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function generateBenefitFormVerificationUrl(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/benefit_form/verification_url', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
