<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * BenefitCategories endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: BenefitCategories
 *
 * @see docs/smart/resources/BenefitCategories.md
 */
class BenefitCategories extends AbstractResource
{
    /**
     * BenefitCategories/List
     *
     * GET /companies/{company_id}/employees/{employee_id}/benefit_categories
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listBenefitCategories(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/benefit_categories', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * BenefitCategories/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/benefit_categories/{benefit_rule_set_id}
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $benefitRuleSetId benefit_rule_set_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getBenefitCategory(string|int $companyId, string|int $employeeId, string|int $benefitRuleSetId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/benefit_categories/{benefit_rule_set_id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'benefit_rule_set_id' => $benefitRuleSetId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
