<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * BenefitGroups endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: BenefitGroups
 *
 * @see docs/smart/resources/BenefitGroups.md
 */
class BenefitGroups extends AbstractResource
{
    /**
     * Companies/BenefitGroups/List
     *
     * GET /companies/{company_id}/benefit_groups
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - limit (integer): Limit for pagination. Defaults to 20 if not provided.
     *   - offset (integer): Offset for pagination. Defaults to 0 if not provided.
     *   - sort (string)
     *   - direction (string): Sort order for the results. Can be "asc" or "desc". Defaults to "asc" if not provided.
     *   - operator (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listBenefitGroups(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/benefit_groups', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/BenefitGroups/List
     *
     * GET /companies/{company_id}/benefit_groups/{id}
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getBenefitGroup(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/benefit_groups/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * BenefitGroups/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/benefit_group
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - age (integer)
     *   - years_of_service (integer)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getEmployeeBenefitGroup(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/benefit_group', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
