<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * BenefitGroupAutoAllocatorResults endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: BenefitGroupAutoAllocatorResults
 *
 * @see docs/smart/resources/BenefitGroupAutoAllocatorResults.md
 */
class BenefitGroupAutoAllocatorResults extends AbstractResource
{
    /**
     * Companies/BenefitGroupAutoAllocatorResults/List
     *
     * GET /companies/{company_id}/benefit_group_auto_allocator_results
     * OAuth scopes: customer
     *
     * Query parameters ($query):
     *   - sort (string)
     *   - direction (string): Sort order for the results. Can be "asc" or "desc". Defaults to "asc" if not provided.
     *   - limit (integer): Limit for pagination. Defaults to 20 if not provided.
     *   - offset (integer): Offset for pagination. Defaults to 0 if not provided.
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: employee_id, state, created_at, employment_period
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listBenefitGroupAutoAllocatorResults(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/benefit_group_auto_allocator_results', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/BenefitGroupAutoAllocatorResults/Get
     *
     * GET /companies/{company_id}/benefit_group_auto_allocator_results/{id}
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getBenefitGroupAutoAllocatorResult(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/benefit_group_auto_allocator_results/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
