<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Cities endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Cities
 *
 * @see docs/smart/resources/Cities.md
 */
class Cities extends AbstractResource
{
    /**
     * Cities/Autocomplete
     *
     * Autocomplete cities by country code and city prefix
     *
     * GET /cities/{country_code}/autocomplete
     * Authentication: none required
     *
     * Query parameters ($query):
     *   - city_prefix (string) required: Prefix of the city name to filter cities
     *   - limit (integer): Limit the number of returned cities
     *   - offset (integer): Offset the results
     *
     * @param string|int $countryCode Country code to filter cities
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function autocompleteCities(string|int $countryCode, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/cities/{country_code}/autocomplete', ['country_code' => $countryCode], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }
}
