<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * CompanySchemeDetails endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: CompanySchemeDetails
 *
 * @see docs/smart/resources/CompanySchemeDetails.md
 */
class CompanySchemeDetails extends AbstractResource
{
    /**
     * Companies/SchemeDetails/Update
     *
     * PUT /companies/{company_id}/scheme_details/{id}
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - starts_on (string)
     *   - renewal_on (string)
     *   - regulator_reference (string)
     *   - revenue_reference (string)
     *   - scheme_id (integer)
     *   - display_name (string)
     *   - tax_relief_basis_type (string)
     *   - tax_relief_fallback_type (string)
     *   - salary_sacrifice_consent_type (string)
     *   - fund_set_id (integer)
     *   - fund_set_name (string)
     *   - instrument_name (string)
     *   - instrument_type (string)
     *   - assessment_required (string)
     *   - metadata (object)
     *   - ae_qualifying (boolean)
     *   - charge_package_name (string)
     *   - charge_package_id (integer)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceSchemeDetail(string|int $companyId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/scheme_details/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
