<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * CompanyBranding endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: CompanyBranding
 *
 * @see docs/smart/resources/CompanyBranding.md
 */
class CompanyBranding extends AbstractResource
{
    /**
     * CompanyBranding/Get
     *
     * GET /companies/{company_id}/company_branding
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getCompanyBranding(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/company_branding', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * CompanyBranding/Create
     *
     * POST /companies/{company_id}/company_branding
     * OAuth scopes: customer
     *
     * Body fields ($body, multipart/form-data):
     *   - description (string)
     *   - logo (file) required
     *   - company_branding_stock_id (integer) required
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body multipart fields; files as fopen() resources or ['contents' => ..., 'filename' => ...]
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createCompanyBranding(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/company_branding', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'multipart' => $body,
        ]);
    }

    /**
     * CompanyBranding/Update
     *
     * PUT /companies/{company_id}/company_branding
     * OAuth scopes: customer
     *
     * Body fields ($body, multipart/form-data):
     *   - description (string)
     *   - logo (file)
     *   - company_branding_stock_id (integer)
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body multipart fields; files as fopen() resources or ['contents' => ..., 'filename' => ...]
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceCompanyBranding(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/company_branding', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'multipart' => $body,
        ]);
    }

    /**
     * CompanyBranding/Update
     *
     * PATCH /companies/{company_id}/company_branding
     * OAuth scopes: customer
     *
     * Body fields ($body, multipart/form-data):
     *   - description (string)
     *   - logo (file)
     *   - company_branding_stock_id (integer)
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body multipart fields; files as fopen() resources or ['contents' => ..., 'filename' => ...]
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateCompanyBranding(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/company_branding', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'multipart' => $body,
        ]);
    }
}
