<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * CompanyAutomations endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: CompanyAutomations
 *
 * @see docs/smart/resources/CompanyAutomations.md
 */
class CompanyAutomations extends AbstractResource
{
    /**
     * CompanyAutomations/Get
     *
     * GET /companies/{company_id}/company_automation
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getCompanyAutomation(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/company_automation', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * CompanyAutomations/Update
     *
     * PUT /companies/{company_id}/company_automation
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - letter (boolean)
     *   - postponement_period (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceCompanyAutomation(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/company_automation', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * CompanyAutomations/Update
     *
     * PATCH /companies/{company_id}/company_automation
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - letter (boolean)
     *   - postponement_period (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateCompanyAutomation(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/company_automation', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
