<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * CompanyFees endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: CompanyFees
 *
 * @see docs/smart/resources/CompanyFees.md
 */
class CompanyFees extends AbstractResource
{
    /**
     * CompanyFees/List
     *
     * GET /companies/{company_id}/company_fees
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: id, total_amount, created_at, starts_on, ends_on, state, processed_at
     *   - include[] (mixed[]): Items one of: `charge_configuration`
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listCompanyFees(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/company_fees', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * CompanyFees/Invoice
     *
     * GET /companies/{company_id}/company_fees/{company_fee_id}/invoice
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $companyFeeId company_fee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getCompanyFeeInvoice(string|int $companyId, string|int $companyFeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/company_fees/{company_fee_id}/invoice', ['company_id' => $companyId, 'company_fee_id' => $companyFeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
