<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * CompanyBrandingStocks endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: CompanyBrandingStocks
 *
 * @see docs/smart/resources/CompanyBrandingStocks.md
 */
class CompanyBrandingStocks extends AbstractResource
{
    /**
     * CompanyBrandingStocks/List
     *
     * GET /company_branding_stocks
     * Authentication: none required
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listCompanyBrandingStocks(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/company_branding_stocks', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }
}
