<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * CompanyLookups endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: CompanyLookups, CompanyLookup
 *
 * @see docs/smart/resources/CompanyLookups.md
 */
class CompanyLookups extends AbstractResource
{
    /**
     * CompanyLookups/List
     *
     * GET /company_lookups
     * Authentication: none required
     *
     * Query parameters ($query):
     *   - name (string)
     *   - countryCode (string)
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listCompanyLookups(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/company_lookups', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * CompanyLookups/Get
     *
     * GET /company_lookups/{country_code}/{id}
     * Authentication: none required
     *
     * @param string|int $countryCode country_code path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getCompanyLookupByCountry(string|int $countryCode, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/company_lookups/{country_code}/{id}', ['country_code' => $countryCode, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * CompanyLookups/Get
     *
     * GET /company_lookups/{id}
     * Authentication: none required
     *
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getCompanyLookup(string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/company_lookups/{id}', ['id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }
}
