<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Companies endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Company, Companies
 *
 * @see docs/smart/resources/Companies.md
 */
class Companies extends AbstractResource
{
    /**
     * Companies/List
     *
     * GET /companies
     * OAuth scopes: user
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: id, name, state, scheme_detail, scheme_details, scheme, adviser_companies, employees, tax_relief_basis_type
     *   - include[] (mixed[]): Items one of: `company_automation`, `scheme_detail`, `scheme_details`, `scheme`, `adviser_companies`, `customers`, `employees`
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listCompanies(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Create
     *
     * POST /companies
     * Authentication: none required
     *
     * Body fields ($body, JSON):
     *   - scheme_origin (string)
     *   - scheme_origin_provider_id (string)
     *   - scheme_origin_provider_name (string)
     *   - name (string) required
     *   - registration_number (string)
     *   - legal_structure (string) required
     *   - tax_office_employer_reference (string)
     *   - tax_office_number (string)
     *   - reg_address1 (string)
     *   - reg_address2 (string)
     *   - reg_address3 (string)
     *   - reg_address4 (string)
     *   - reg_address_postcode (string)
     *   - reg_address_country_code (string)
     *   - trading_address1 (string)
     *   - trading_address2 (string)
     *   - trading_address3 (string)
     *   - trading_address4 (string)
     *   - trading_address_postcode (string)
     *   - trading_address_country_code (string)
     *   - state_of_incorporation (string)
     *   - taxed_as (string)
     *   - tax_year_end_day (integer)
     *   - tax_year_end_month (integer)
     *   - national_insurance_saving_share (number)
     *   - pensionable_earning_type (string)
     *   - pension_regulator_letter_code (string)
     *   - default_percentage (number)
     *   - signatories (object[])
     *   - admins (object[])
     *   - scheme_details (object[])
     *   - scheme_starts_on (string)
     *   - enrolment_event_on (string)
     *   - tax_registration_number (mixed)
     *   - adviser_token (mixed)
     *   - incorporated_on (string)
     *   - employee_can_change_contribution (boolean)
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createCompany(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * CompaniesBySlug/Get
     *
     * GET /companies/by_slug
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - slug (string)
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getCompanyBySlug(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/by_slug', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Get
     *
     * GET /companies/{company_id}
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - include[] (mixed[]): Items one of: `company_automation`, `benefit_groups`, `payroll_configurations`, `scheme_detail`, `scheme_detail.company_tax_reliefs`, `scheme_details`, `employee`, `envelope`, `customers`, `know_your_customer_data`, `bank_account_details`, `scheme`, `scheme.bank_detail`, `economic_zone`, `adviser_companies`
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getCompany(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Update
     *
     * PUT /companies/{company_id}
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - scheme_origin (string)
     *   - scheme_origin_provider_id (string)
     *   - scheme_origin_provider_name (string)
     *   - name (string)
     *   - registration_number (string)
     *   - legal_structure (string)
     *   - tax_office_employer_reference (string)
     *   - tax_office_number (string)
     *   - reg_address1 (string)
     *   - reg_address2 (string)
     *   - reg_address3 (string)
     *   - reg_address4 (string)
     *   - reg_address_postcode (string)
     *   - reg_address_country_code (string)
     *   - trading_address1 (string)
     *   - trading_address2 (string)
     *   - trading_address3 (string)
     *   - trading_address4 (string)
     *   - trading_address_postcode (string)
     *   - trading_address_country_code (string)
     *   - state_of_incorporation (string)
     *   - taxed_as (string)
     *   - tax_year_end_day (integer)
     *   - tax_year_end_month (integer)
     *   - national_insurance_saving_share (number)
     *   - pensionable_earning_type (string)
     *   - pension_regulator_letter_code (string)
     *   - default_percentage (number)
     *   - slug (string)
     *   - state (string)
     *   - scheme_detail (object)
     *   - adviser_id (integer)
     *   - preferred_contact_user_id (integer)
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceCompany(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Update
     *
     * PATCH /companies/{company_id}
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - scheme_origin (string)
     *   - scheme_origin_provider_id (string)
     *   - scheme_origin_provider_name (string)
     *   - name (string)
     *   - registration_number (string)
     *   - legal_structure (string)
     *   - tax_office_employer_reference (string)
     *   - tax_office_number (string)
     *   - reg_address1 (string)
     *   - reg_address2 (string)
     *   - reg_address3 (string)
     *   - reg_address4 (string)
     *   - reg_address_postcode (string)
     *   - reg_address_country_code (string)
     *   - trading_address1 (string)
     *   - trading_address2 (string)
     *   - trading_address3 (string)
     *   - trading_address4 (string)
     *   - trading_address_postcode (string)
     *   - trading_address_country_code (string)
     *   - state_of_incorporation (string)
     *   - taxed_as (string)
     *   - tax_year_end_day (integer)
     *   - tax_year_end_month (integer)
     *   - national_insurance_saving_share (number)
     *   - pensionable_earning_type (string)
     *   - pension_regulator_letter_code (string)
     *   - default_percentage (number)
     *   - slug (string)
     *   - state (string)
     *   - scheme_detail (object)
     *   - adviser_id (integer)
     *   - preferred_contact_user_id (integer)
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateCompany(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Schemes/List
     *
     * GET /companies/{company_id}/schemes
     * OAuth scopes: customer
     *
     * @param string|int $companyId ID of the company
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listSchemes(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/schemes', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
