<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Constants endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Constants
 *
 * @see docs/smart/resources/Constants.md
 */
class Constants extends AbstractResource
{
    /**
     * Constants/Get
     *
     * GET /constants
     * Authentication: none required
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getConstants(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/constants', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }
}
