<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Contributions endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Contribution, Contributions
 *
 * @see docs/smart/resources/Contributions.md
 */
class Contributions extends AbstractResource
{
    /**
     * Companies/Contributions/List with Historical Employee Data
     *
     * Lists contributions for a company. When the 'exited_employees_visibility' feature flag is enabled,
     * contributions for employees who exited more than 6 weeks ago will display historical employee data
     * (forename, surname, and national_insurance_number as they were at the time of exit) instead of
     * current data.
     *
     * GET /companies/{company_id}/contributions
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: state, period_type, starts_on, ends_on, pensionable_earnings, employee_amount, employee_percentage, company_amount, company_percentage, voluntary_amount, employee_id, employee, assessment, ni_rebate_amount, total_employee_amount, employee_sal_sac_amount, scheme
     *   - include[] (mixed[]): Items one of: `assessment`, `employee`, `scheme`
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listCompanyContributions(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/contributions', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Contributions/List
     *
     * GET /companies/{company_id}/employees/{employee_id}/contributions
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: state, assessment, period_type, starts_on, ends_on
     *   - include[] (mixed[]): Items one of: `assessment`
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listEmployeeContributions(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/contributions', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Contributions/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/contributions
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - starts_on (string)
     *   - ends_on (string)
     *   - period_type (string)
     *   - category (string)
     *   - contribution_type (string)
     *   - type (string)
     *   - pensionable_earnings (number)
     *   - gross_qualifying_earnings (number)
     *   - second_gross_qualifying_earnings_amount (number)
     *   - unusual_amount_reason (string)
     *   - group_name (string)
     *   - company_amount (number)
     *   - employee_amount (number)
     *   - employee_percentage (number)
     *   - company_percentage (number)
     *   - avc_percentage (number)
     *   - voluntary_amount (number)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createContribution(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/contributions', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Contributions/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/contributions/{id}
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - include[] (mixed[]): Items one of: `employee`
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getContribution(string|int $companyId, string|int $employeeId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/contributions/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Contributions/Update
     *
     * PUT /companies/{company_id}/employees/{employee_id}/contributions/{id}
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceContribution(string|int $companyId, string|int $employeeId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/employees/{employee_id}/contributions/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Contributions/Update
     *
     * PATCH /companies/{company_id}/employees/{employee_id}/contributions/{id}
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateContribution(string|int $companyId, string|int $employeeId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{employee_id}/contributions/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Contributions/Destroy
     *
     * DELETE /companies/{company_id}/employees/{employee_id}/contributions/{id}
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deleteContribution(string|int $companyId, string|int $employeeId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/companies/{company_id}/employees/{employee_id}/contributions/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
