<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Countries endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Countries, LegalBankLocation, Nationalities
 *
 * @see docs/smart/resources/Countries.md
 */
class Countries extends AbstractResource
{
    /**
     * Countries/List
     *
     * GET /countries
     * Authentication: none required
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listCountries(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/countries', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * Countries/LegalBankLocation/List
     *
     * GET /countries/legal_bank_location
     * Authentication: none required
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listLegalBankLocations(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/countries/legal_bank_location', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * Countries/Nationality/List
     *
     * GET /countries/nationality
     * Authentication: none required
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listNationalities(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/countries/nationality', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }
}
