<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Currencies endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Currency
 *
 * @see docs/smart/resources/Currencies.md
 */
class Currencies extends AbstractResource
{
    /**
     * Currencies/List
     *
     * GET /currencies
     * Authentication: none required
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listCurrencies(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/currencies', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }
}
