<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * CustomerLeads endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: CustomerLead
 *
 * @see docs/smart/resources/CustomerLeads.md
 */
class CustomerLeads extends AbstractResource
{
    /**
     * CustomerLeads/Create
     *
     * POST /customer_leads/
     * Authentication: none required
     *
     * Body fields ($body, JSON):
     *   - last_name (string) required
     *   - first_name (string) required
     *   - email (string) required
     *   - role (string) required
     *   - other_role (string)
     *   - telephone (string) required
     *   - company_name (string) required
     *   - privacy_policy_accepted (boolean)
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createCustomerLead(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/customer_leads/', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * CustomerLeads/EarliestPlanEffectiveDate
     *
     * GET /customer_leads/earliest_plan_effective_date
     * Authentication: none required
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getEarliestPlanEffectiveDate(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/customer_leads/earliest_plan_effective_date', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * Companies/Get
     *
     * GET /customer_leads/{customer_lead_id}
     * Authentication: none required
     *
     * Headers ($headers):
     *   - Token
     *
     * @param string|int $customerLeadId customer_lead_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getCustomerLead(string|int $customerLeadId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/customer_leads/{customer_lead_id}', ['customer_lead_id' => $customerLeadId], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }
}
