<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * CustomAppStyling endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: CustomAppStyling
 *
 * @see docs/smart/resources/CustomAppStyling.md
 */
class CustomAppStyling extends AbstractResource
{
    /**
     * CustomAppStyling/Get
     *
     * GET /companies/{company_id}/style
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getStyle(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/style', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
