<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Customers endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Customer
 *
 * @see docs/smart/resources/Customers.md
 */
class Customers extends AbstractResource
{
    /**
     * Customers/List
     *
     * GET /companies/{company_id}/customers
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: id, referee_id, role, envelope_state, forename, surname, email
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listCustomers(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/customers', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Customers/Create
     *
     * POST /companies/{company_id}/customers
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - date_of_birth (string) required
     *   - title (string)
     *   - forename (string) required
     *   - middlename (string)
     *   - surname (string) required
     *   - telephone (string)
     *   - alternative_telephone (string)
     *   - line1 (string)
     *   - line2 (string)
     *   - city (string)
     *   - county (string)
     *   - postcode (string) required
     *   - email (string) required
     *   - building_name (string)
     *   - building_number (string)
     *   - gender (string)
     *   - country_code (string)
     *   - preferred_locale (string)
     *   - role (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createCustomer(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/customers', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Customers/Get
     *
     * GET /companies/{company_id}/customers/{id}
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - include[] (mixed[]): Items one of: `company`, `company.scheme_detail`, `company.scheme_detail.company_tax_reliefs`, `company.scheme_details`, `company.know_your_customer_data`, `company.payroll_configurations`, `company.benefit_groups`, `company.bank_account_details`, `company.scheme`, `company.scheme.bank_detail`, `company.provider_scheme_migration`, `company.economic_zone`, `employee`, `employee.contributions`, `shortcut`
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getCustomer(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/customers/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Customers/Update
     *
     * PUT /companies/{company_id}/customers/{id}
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - date_of_birth (string)
     *   - title (string)
     *   - forename (string)
     *   - middlename (string)
     *   - surname (string)
     *   - telephone (string)
     *   - alternative_telephone (string)
     *   - line1 (string)
     *   - line2 (string)
     *   - city (string)
     *   - county (string)
     *   - postcode (string)
     *   - email (string)
     *   - building_name (string)
     *   - building_number (string)
     *   - gender (string)
     *   - country_code (string)
     *   - preferred_locale (string)
     *   - password (string)
     *   - current_password (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceCustomer(string|int $companyId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/customers/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Customers/Update
     *
     * PATCH /companies/{company_id}/customers/{id}
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - date_of_birth (string)
     *   - title (string)
     *   - forename (string)
     *   - middlename (string)
     *   - surname (string)
     *   - telephone (string)
     *   - alternative_telephone (string)
     *   - line1 (string)
     *   - line2 (string)
     *   - city (string)
     *   - county (string)
     *   - postcode (string)
     *   - email (string)
     *   - building_name (string)
     *   - building_number (string)
     *   - gender (string)
     *   - country_code (string)
     *   - preferred_locale (string)
     *   - password (string)
     *   - current_password (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateCustomer(string|int $companyId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/customers/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Customers/Destroy
     *
     * DELETE /companies/{company_id}/customers/{id}
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deleteCustomer(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/companies/{company_id}/customers/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Envelope/Reminds/Create
     *
     * POST /companies/{company_id}/envelope/remind
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function remindEnvelopeSigners(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/envelope/remind', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Customers/Session
     *
     * GET /customers/session
     * OAuth scopes: customer
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getCustomerSession(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/customers/session', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
