<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * CustomerRoles endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Role
 *
 * @see docs/smart/resources/CustomerRoles.md
 */
class CustomerRoles extends AbstractResource
{
    /**
     * Customers/Roles/Create
     *
     * POST /companies/{company_id}/customers/{customer_id}/role
     * OAuth scopes: user
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $customerId customer_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createCustomerRole(string|int $companyId, string|int $customerId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/customers/{customer_id}/role', ['company_id' => $companyId, 'customer_id' => $customerId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Customers/Roles/Update
     *
     * PATCH /companies/{company_id}/customers/{customer_id}/role
     * OAuth scopes: user
     *
     * Body fields ($body, JSON):
     *   - admin_id (integer)
     *   - signatory_id (integer)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $customerId customer_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateCustomerRole(string|int $companyId, string|int $customerId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/customers/{customer_id}/role', ['company_id' => $companyId, 'customer_id' => $customerId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Customers/Roles/Destroy
     *
     * DELETE /companies/{company_id}/customers/{customer_id}/role
     * OAuth scopes: user
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $customerId customer_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deleteCustomerRole(string|int $companyId, string|int $customerId, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/companies/{company_id}/customers/{customer_id}/role', ['company_id' => $companyId, 'customer_id' => $customerId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
