<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * DeclarationOfComplianceEmployeeTotals endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: DeclarationOfComplianceEmployeeTotals
 *
 * @see docs/smart/resources/DeclarationOfComplianceEmployeeTotals.md
 */
class DeclarationOfComplianceEmployeeTotals extends AbstractResource
{
    /**
     * DeclarationOfComplianceEmployeeTotals/List
     *
     * GET /companies/{company_id}/declaration_of_compliance_employee_totals
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listDeclarationOfComplianceEmployeeTotals(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/declaration_of_compliance_employee_totals', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
