<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * EconomicZones endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: EconomicZone
 *
 * @see docs/smart/resources/EconomicZones.md
 */
class EconomicZones extends AbstractResource
{
    /**
     * EconomicZones/Get
     *
     * GET /economic_zones
     * Authentication: none required
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listEconomicZones(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/economic_zones', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }
}
