<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Employees endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Employee, untagged
 *
 * @see docs/smart/resources/Employees.md
 */
class Employees extends AbstractResource
{
    /**
     * Companies/Employees/List with Historical Employee Data
     *
     * Lists employees for a company. When the 'exited_employees_visibility' feature flag is enabled,
     * employees who exited more than 6 weeks ago will display historical employee data
     * (forename, surname, national_insurance_number, email, gender, date_of_birth, and telephone
     * as they were at the time of exit) instead of current data. These records are marked with
     * 'is_not_editable: true' to indicate they should not be modified.
     *
     * GET /companies/{company_id}/employees
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: id, forename, surname, external_id, national_insurance_number, retirement_age, retirement_date, employee_plan_participation, updated_at, employee_contribution_configurations, opt_state, starts_on, ends_on, opt_out_on, opt_in_on, exit_reason, benefit_group_id, group_id
     *   - include[] (mixed[]): Items one of: `contributions`, `group`, `postponements`, `employee_plan_participation`, `employee_contribution_configurations`, `employment_category`
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listEmployees(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Employees/Create
     *
     * POST /companies/{company_id}/employees
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - date_of_birth (string) required
     *   - starts_on (string) required
     *   - ends_on (string)
     *   - title (string)
     *   - forename (string) required
     *   - surname (string) required
     *   - telephone (string)
     *   - external_id (string)
     *   - external_oidc_id (string)
     *   - email (string)
     *   - national_insurance_number (string)
     *   - exit_reason (string)
     *   - opt_state (string)
     *   - event_date (string)
     *   - event_code (string)
     *   - gender (string) required
     *   - percentage (number)
     *   - company_percentage (number)
     *   - company_match (boolean)
     *   - group_id (integer)
     *   - works_in_uk (boolean)
     *   - contribute_if_entitled (boolean)
     *   - customer_id (integer)
     *   - retirement_age (integer)
     *   - retirement_date (string)
     *   - scheme_origin (string)
     *   - secondary_email (string)
     *   - middle_name (string)
     *   - civil_status (string)
     *   - effective_date (string)
     *   - employment_status (string)
     *   - part_time_percentage (number)
     *   - line1 (string)
     *   - line2 (string)
     *   - city (string)
     *   - postcode (string) required
     *   - employment_category (string)
     *   - contractual_enrolment (boolean)
     *   - target_retirement_age (integer)
     *   - line3 (string)
     *   - employment_type (string)
     *   - tax_residency_status_name (string)
     *   - country_code (string)
     *   - avc_percentage (number)
     *   - salary_sacrifice_signed (boolean)
     *   - annual_earnings1 (number)
     *   - annual_earnings2 (number)
     *   - region (string)
     *   - benefit_group_assigned_at (string)
     *   - opt_in_on (string)
     *   - minimum_percentage (number)
     *   - maximum_percentage (number)
     *   - minimum_company_percentage (number)
     *   - maximum_company_percentage (number)
     *   - minimum_roth_percentage (number)
     *   - maximum_roth_percentage (number)
     *   - skip_group_assignment (boolean)
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createEmployee(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * ActivePayrollConfiguration/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/active_payroll_configuration
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getActivePayrollConfiguration(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/active_payroll_configuration', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Employees/GenerateIfaReport
     *
     * POST /companies/{company_id}/employees/{employee_id}/generate_ifa_report
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function generateIfaReport(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/generate_ifa_report', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Employees/PresignedPost/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/presigned_post
     * OAuth scopes: user, employee
     *
     * Body fields ($body, JSON):
     *   - path (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createPresignedPost(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/presigned_post', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Employees/RecurringContributionSchedule/Show
     *
     * GET /companies/{company_id}/employees/{employee_id}/recurring_contribution_schedule
     * OAuth scopes: user, employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getRecurringContributionSchedule(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/recurring_contribution_schedule', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Employees/RecurringContributionSchedule/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/recurring_contribution_schedule
     * OAuth scopes: user, employee
     *
     * Body fields ($body, JSON):
     *   - day_of_month (integer)
     *   - annual_allowance_confirmation (boolean)
     *   - amount (number)
     *   - success_url (string)
     *   - failure_url (string)
     *   - source_of_funds (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createRecurringContributionSchedule(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/recurring_contribution_schedule', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Employees/RecurringContributionSchedule/Update
     *
     * PATCH /companies/{company_id}/employees/{employee_id}/recurring_contribution_schedule
     * OAuth scopes: user, employee
     *
     * Body fields ($body, JSON):
     *   - day_of_month (integer)
     *   - annual_allowance_confirmation (boolean)
     *   - amount (number)
     *   - success_url (string)
     *   - failure_url (string)
     *   - source_of_funds (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateRecurringContributionSchedule(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{employee_id}/recurring_contribution_schedule', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Employees/RecurringContributionSchedule/Destroy
     *
     * DELETE /companies/{company_id}/employees/{employee_id}/recurring_contribution_schedule
     * OAuth scopes: user, employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deleteRecurringContributionSchedule(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/companies/{company_id}/employees/{employee_id}/recurring_contribution_schedule', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Employees/SingleContributionPayments/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/single_contribution_payments
     * OAuth scopes: user, employee
     *
     * Body fields ($body, JSON):
     *   - amount (number) required
     *   - annual_allowance_confirmation (boolean) required
     *   - success_url (string) required
     *   - failure_url (string) required
     *   - source_of_funds (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createSingleContributionPayment(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/single_contribution_payments', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Employees/TaxResidences/VerifyHomeCountry
     *
     * GET /companies/{company_id}/employees/{employee_id}/tax_residence/verify_home_country
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function verifyTaxResidenceHomeCountry(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/tax_residence/verify_home_country', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Employees/Get
     *
     * GET /companies/{company_id}/employees/{id}
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - include[] (mixed[]): Items one of: `company`, `company.scheme_detail`, `company.scheme_detail.current_company_tax_relief`, `company.scheme_details`, `company.scheme_details.current_company_tax_relief`, `company.default_investment_instrument`, `company.economic_zone`, `company.scheme`, `customer`, `shortcut`, `marketing_preference`, `employee_configuration`, `portfolios`, `valuations`, `contributions`, `expression_of_wish`, `employee_plan_participation`, `employment_statuses`, `salaries`, `employment_category`
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getEmployee(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Employees/Update
     *
     * PUT /companies/{company_id}/employees/{id}
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - date_of_birth (string)
     *   - starts_on (string)
     *   - ends_on (string)
     *   - title (string)
     *   - forename (string)
     *   - surname (string)
     *   - telephone (string)
     *   - external_id (string)
     *   - external_oidc_id (string)
     *   - email (string)
     *   - national_insurance_number (string)
     *   - exit_reason (string)
     *   - opt_state (string)
     *   - event_date (string)
     *   - event_code (string)
     *   - gender (string)
     *   - percentage (number)
     *   - company_percentage (number)
     *   - company_match (boolean)
     *   - group_id (integer)
     *   - works_in_uk (boolean)
     *   - contribute_if_entitled (boolean)
     *   - customer_id (integer)
     *   - retirement_age (integer)
     *   - retirement_date (string)
     *   - scheme_origin (string)
     *   - secondary_email (string)
     *   - middle_name (string)
     *   - civil_status (string)
     *   - effective_date (string)
     *   - employment_status (string)
     *   - part_time_percentage (number)
     *   - line1 (string)
     *   - line2 (string)
     *   - city (string)
     *   - postcode (string)
     *   - employment_category (string)
     *   - contractual_enrolment (boolean)
     *   - target_retirement_age (integer)
     *   - line3 (string)
     *   - employment_type (string)
     *   - tax_residency_status_name (string)
     *   - country_code (string)
     *   - avc_percentage (number)
     *   - salary_sacrifice_signed (boolean)
     *   - annual_earnings1 (number)
     *   - annual_earnings2 (number)
     *   - region (string)
     *   - password (string)
     *   - identity_person_id (string)
     *   - current_password (string)
     *   - opt_out_window_starts_on (string)
     *   - opt_in_on (string)
     *   - opt_out_on (string)
     *   - onboarded_at (string)
     *   - online_login_disabled (boolean)
     *   - employee_contribution_configuration_starts_at (string)
     *   - opt_out_reason (string)
     *   - contribution_percentages_confirmed (boolean)
     *   - moved_to_eu_company (boolean)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceEmployee(string|int $companyId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/employees/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Employees/Update
     *
     * PATCH /companies/{company_id}/employees/{id}
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - date_of_birth (string)
     *   - starts_on (string)
     *   - ends_on (string)
     *   - title (string)
     *   - forename (string)
     *   - surname (string)
     *   - telephone (string)
     *   - external_id (string)
     *   - external_oidc_id (string)
     *   - email (string)
     *   - national_insurance_number (string)
     *   - exit_reason (string)
     *   - opt_state (string)
     *   - event_date (string)
     *   - event_code (string)
     *   - gender (string)
     *   - percentage (number)
     *   - company_percentage (number)
     *   - company_match (boolean)
     *   - group_id (integer)
     *   - works_in_uk (boolean)
     *   - contribute_if_entitled (boolean)
     *   - customer_id (integer)
     *   - retirement_age (integer)
     *   - retirement_date (string)
     *   - scheme_origin (string)
     *   - secondary_email (string)
     *   - middle_name (string)
     *   - civil_status (string)
     *   - effective_date (string)
     *   - employment_status (string)
     *   - part_time_percentage (number)
     *   - line1 (string)
     *   - line2 (string)
     *   - city (string)
     *   - postcode (string)
     *   - employment_category (string)
     *   - contractual_enrolment (boolean)
     *   - target_retirement_age (integer)
     *   - line3 (string)
     *   - employment_type (string)
     *   - tax_residency_status_name (string)
     *   - country_code (string)
     *   - avc_percentage (number)
     *   - salary_sacrifice_signed (boolean)
     *   - annual_earnings1 (number)
     *   - annual_earnings2 (number)
     *   - region (string)
     *   - password (string)
     *   - identity_person_id (string)
     *   - current_password (string)
     *   - opt_out_window_starts_on (string)
     *   - opt_in_on (string)
     *   - opt_out_on (string)
     *   - onboarded_at (string)
     *   - online_login_disabled (boolean)
     *   - employee_contribution_configuration_starts_at (string)
     *   - opt_out_reason (string)
     *   - contribution_percentages_confirmed (boolean)
     *   - moved_to_eu_company (boolean)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateEmployee(string|int $companyId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Employees/Destroy
     *
     * DELETE /companies/{company_id}/employees/{id}
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deleteEmployee(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/companies/{company_id}/employees/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Employees/MovedToEuCompany
     *
     * PATCH /companies/{company_id}/employees/{id}/moved_to_eu_company
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - moved_to_eu_company (boolean)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function markMovedToEuCompany(string|int $companyId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{id}/moved_to_eu_company', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Employees/OptStates/Get
     *
     * GET /companies/{company_id}/employees/{id}/opt_state
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getOptState(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{id}/opt_state', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Employees/Retirement
     *
     * GET /employees/retirement
     * OAuth scopes: employee
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getRetirement(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/employees/retirement', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Employees/RetirementOptions
     *
     * GET /employees/retirement_options
     * OAuth scopes: employee
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getRetirementOptions(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/employees/retirement_options', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Employees/Session
     *
     * GET /employees/session
     * OAuth scopes: employee
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getEmployeeSession(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/employees/session', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
