<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * EmployeeConfigurations endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: EmployeeConfiguration
 *
 * @see docs/smart/resources/EmployeeConfigurations.md
 */
class EmployeeConfigurations extends AbstractResource
{
    /**
     * EmployeeConfiguration/Update
     *
     * PUT /companies/{company_id}/employees/{employee_id}/employee_configurations
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - benefits_out_suspended (boolean)
     *   - valuation_under_review (boolean)
     *   - disabled_switching (boolean)
     *   - gone_away (boolean)
     *   - blocked_rejoin (boolean)
     *   - subject_to_money_purchase_annual_allowance (boolean)
     *   - enable_auto_increase_percentage (boolean)
     *   - investments_locked (boolean)
     *   - money_purchase_annual_allowance_effective_on (string)
     *   - preferred_currency (string)
     *   - preferred_locale (string)
     *   - requires_income_adequacy_page_visit (boolean)
     *   - contribution_percentages_confirmed (boolean)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceEmployeeConfigurations(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/employees/{employee_id}/employee_configurations', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * EmployeeConfiguration/Update
     *
     * PATCH /companies/{company_id}/employees/{employee_id}/employee_configurations
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - benefits_out_suspended (boolean)
     *   - valuation_under_review (boolean)
     *   - disabled_switching (boolean)
     *   - gone_away (boolean)
     *   - blocked_rejoin (boolean)
     *   - subject_to_money_purchase_annual_allowance (boolean)
     *   - enable_auto_increase_percentage (boolean)
     *   - investments_locked (boolean)
     *   - money_purchase_annual_allowance_effective_on (string)
     *   - preferred_currency (string)
     *   - preferred_locale (string)
     *   - requires_income_adequacy_page_visit (boolean)
     *   - contribution_percentages_confirmed (boolean)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateEmployeeConfigurations(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{employee_id}/employee_configurations', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
