<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * EmploymentPeriods endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: EmploymentPeriods
 *
 * @see docs/smart/resources/EmploymentPeriods.md
 */
class EmploymentPeriods extends AbstractResource
{
    /**
     * Employees/EmploymentPeriods/List
     *
     * GET /employees/employment_periods
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys:
     *   - include[] (mixed[]): Items one of: `employee`, `company`
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listEmploymentPeriods(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/employees/employment_periods', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
