<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * EmployeeFundHoldings endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: EmployeeFundHoldings
 *
 * @see docs/smart/resources/EmployeeFundHoldings.md
 */
class EmployeeFundHoldings extends AbstractResource
{
    /**
     * Companies/Employees/EmployeeFundHoldings/List
     *
     * GET /companies/{company_id}/employees/{employee_id}/employee_fund_holdings
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listEmployeeFundHoldings(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/employee_fund_holdings', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Employees/EmployeeFundHoldings/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/employee_fund_holdings/{id}
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getEmployeeFundHolding(string|int $companyId, string|int $employeeId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/employee_fund_holdings/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Employees/EmployeeFundsValuations/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/employee_funds_valuations
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - subaccount_uuid (string)
     *   - investment_account_uuids[] (string[])
     *   - pots[] (string[])
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getEmployeeFundsValuations(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/employee_funds_valuations', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
