<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * EmployeeExternalPensions endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: EmployeeExternalPensions
 *
 * @see docs/smart/resources/EmployeeExternalPensions.md
 */
class EmployeeExternalPensions extends AbstractResource
{
    /**
     * Companies/Employees/EmployeeExternalPensions/List
     *
     * GET /companies/{company_id}/employees/{employee_id}/employee_external_pensions
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listEmployeeExternalPensions(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/employee_external_pensions', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Employees/EmployeeExternalPensions/BulkUpdate
     *
     * POST /companies/{company_id}/employees/{employee_id}/employee_external_pensions/bulk_update
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - employee_external_pensions (object[])
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function bulkUpdateEmployeeExternalPensions(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/employee_external_pensions/bulk_update', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
