<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * EmployeeVerificationChecks endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: EmployeeVerificationChecks
 *
 * @see docs/smart/resources/EmployeeVerificationChecks.md
 */
class EmployeeVerificationChecks extends AbstractResource
{
    /**
     * VerificationChecks/GenerateVerificationUrl
     *
     * POST /companies/{company_id}/employees/{employee_id}/verification_checks/generate_verification_url
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - redirect_url (string) required
     *   - target (string) required
     *   - service_name (string)
     *   - verification_check_types (mixed[])
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function generateVerificationUrl(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/verification_checks/generate_verification_url', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * VerificationChecks/State
     *
     * GET /companies/{company_id}/employees/{employee_id}/verification_checks/state
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - target (string) required: One of: `'onboarding'`, `'single_contributions'`, `'benefit_form'`
     *   - verification_check_types[] (mixed[])
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getVerificationCheckState(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/verification_checks/state', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * VerificationChecks/GetVerificationUrl
     *
     * GET /companies/{company_id}/employees/{employee_id}/verification_checks/verification_url
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - target (string): One of: `'onboarding'`, `'single_contributions'`, `'benefit_form'`
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getVerificationUrl(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/verification_checks/verification_url', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
