<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * EmployeeRateRecommendations endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: EmployeeRateRecommendation
 *
 * @see docs/smart/resources/EmployeeRateRecommendations.md
 */
class EmployeeRateRecommendations extends AbstractResource
{
    /**
     * Companies/Employees/EmployeeRateRecommendation/Create
     *
     * POST /companies/{company_id}/employees/{id}/employee_rate_recommendation
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - target_annual_pension (number) required
     *   - include_state_pension (boolean)
     *   - retirement_age (integer)
     *   - one_off_payment (number)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createEmployeeRateRecommendation(string|int $companyId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{id}/employee_rate_recommendation', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
