<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * EnrolmentEmployees endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: EnrolmentEmployees
 *
 * @see docs/smart/resources/EnrolmentEmployees.md
 */
class EnrolmentEmployees extends AbstractResource
{
    /**
     * Companies/Enrolments/Employees/List
     *
     * GET /companies/{company_id}/enrolments/{enrolment_id}/employees
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: id, forename, surname, external_id, slug, email, opt_state, ends_on, group_id, exit_reason, company_match
     *   - operator (string): One of: `'or'`, `'and'`
     *   - type (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $enrolmentId enrolment_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listEnrolmentEmployees(string|int $companyId, string|int $enrolmentId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/enrolments/{enrolment_id}/employees', ['company_id' => $companyId, 'enrolment_id' => $enrolmentId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
