<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Envelopes endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Envelopes, EnvelopeSigning
 *
 * @see docs/smart/resources/Envelopes.md
 */
class Envelopes extends AbstractResource
{
    /**
     * Companies/Envelopes/Get
     *
     * GET /companies/{company_id}/envelope
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getEnvelope(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/envelope', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Envelope/Signing
     *
     * GET /companies/{company_id}/envelope/signing
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getEnvelopeSigning(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/envelope/signing', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
