<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * EstimateBenefitValuations endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: EstimateBenefitValuations
 *
 * @see docs/smart/resources/EstimateBenefitValuations.md
 */
class EstimateBenefitValuations extends AbstractResource
{
    /**
     * EstimateBenefitValuations/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/benefit_categories/{benefit_category_id}/estimate_benefit_valuations
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - subaccount_uuid (string)
     *   - requested_benefit_amount (integer) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $benefitCategoryId benefit_category_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getEstimateBenefitValuations(string|int $companyId, string|int $employeeId, string|int $benefitCategoryId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/benefit_categories/{benefit_category_id}/estimate_benefit_valuations', ['company_id' => $companyId, 'employee_id' => $employeeId, 'benefit_category_id' => $benefitCategoryId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
