<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Exports endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Exports
 *
 * @see docs/smart/resources/Exports.md
 */
class Exports extends AbstractResource
{
    /**
     * Exports/List
     *
     * GET /advisers/{adviser_id}/exports
     * OAuth scopes: user
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: state, created_at, type
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $adviserId adviser_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listExports(string|int $adviserId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/advisers/{adviser_id}/exports', ['adviser_id' => $adviserId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Exports/Create
     *
     * POST /advisers/{adviser_id}/exports
     * OAuth scopes: user
     *
     * Body fields ($body, JSON):
     *   - metadata (object)
     *   - type (string) required
     *   - content_type (string) required
     *   - file_format (string) required
     *   - resource_type (string)
     *   - resource_id (integer)
     *
     * @param string|int $adviserId adviser_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createExport(string|int $adviserId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/advisers/{adviser_id}/exports', ['adviser_id' => $adviserId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
