<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * ExternalEmployeeDataAvailability endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: ExternalEmployeeDataAvailability
 *
 * @see docs/smart/resources/ExternalEmployeeDataAvailability.md
 */
class ExternalEmployeeDataAvailability extends AbstractResource
{
    /**
     * Companies/ExternalEmployeeDataAvailability/Get
     *
     * GET /companies/{company_id}/external_employee_data_availability
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getExternalEmployeeDataAvailability(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/external_employee_data_availability', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
