<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * FeatureFlags endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: FeatureFlags
 *
 * @see docs/smart/resources/FeatureFlags.md
 */
class FeatureFlags extends AbstractResource
{
    /**
     * FeatureFlags/List
     *
     * GET /feature_flags
     * OAuth scopes: user
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listFeatureFlags(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/feature_flags', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
