<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Glidepaths endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Glidepaths
 *
 * @see docs/smart/resources/Glidepaths.md
 */
class Glidepaths extends AbstractResource
{
    /**
     * Glidepaths/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/glidepaths
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - glidepath (object)
     *   - subaccount_uuid (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createGlidepath(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/glidepaths', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
