<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Imports endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Import
 *
 * @see docs/smart/resources/Imports.md
 */
class Imports extends AbstractResource
{
    /**
     * Import/List
     *
     * GET /companies/{company_id}/imports
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: state, created_at, type
     *   - include[] (mixed[]): Items one of: `adviser`
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listImports(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/imports', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Import/Create
     *
     * POST /companies/{company_id}/imports
     * OAuth scopes: user, customer
     *
     * Body fields ($body, multipart/form-data):
     *   - metadata (object)
     *   - file (file) required
     *   - type (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body multipart fields; files as fopen() resources or ['contents' => ..., 'filename' => ...]
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createImport(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/imports', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'multipart' => $body,
        ]);
    }

    /**
     * Import/Get
     *
     * GET /companies/{company_id}/imports/{id}
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getImport(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/imports/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Import/ImportResults/List
     *
     * GET /companies/{company_id}/imports/{import_id}/import_results
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: state
     *   - include[] (mixed[]): Items one of: `import`
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $importId import_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listImportResults(string|int $companyId, string|int $importId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/imports/{import_id}/import_results', ['company_id' => $companyId, 'import_id' => $importId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
