<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Individuals endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Individual
 *
 * @see docs/smart/resources/Individuals.md
 */
class Individuals extends AbstractResource
{
    /**
     * Individuals/RetirementAge
     *
     * PUT /individuals/retirement_age
     * OAuth scopes: individual
     *
     * Body fields ($body, JSON):
     *   - retirement_age (integer) required
     *
     * Headers ($headers):
     *   - X-Account-Id required: Account ID
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateRetirementAge(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/individuals/retirement_age', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
