<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * InvestmentsPerformance endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: InvestmentsPerformance
 *
 * @see docs/smart/resources/InvestmentsPerformance.md
 */
class InvestmentsPerformance extends AbstractResource
{
    /**
     * InvestmentsPerformance/List
     *
     * GET /companies/{company_id}/employees/{employee_id}/investments_performance
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - start_date (string)
     *   - end_date (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getInvestmentsPerformance(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/investments_performance', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
