<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Letters endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Letters, Letter
 *
 * @see docs/smart/resources/Letters.md
 */
class Letters extends AbstractResource
{
    /**
     * Companies/Employees/Letters/List
     *
     * GET /companies/{company_id}/employees/{employee_id}/letters
     * OAuth scopes: customer
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: read, employee_id, name, created_at
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listLetters(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/letters', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Letters/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/letters
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - name (string)
     *   - created_at (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createLetter(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/letters', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Letters/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/letters/{id}
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getLetter(string|int $companyId, string|int $employeeId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/letters/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Employees/Letters/Update
     *
     * PUT /companies/{company_id}/employees/{employee_id}/letters/{id}
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceLetter(string|int $companyId, string|int $employeeId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/employees/{employee_id}/letters/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Employees/Letters/Update
     *
     * PATCH /companies/{company_id}/employees/{employee_id}/letters/{id}
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateLetter(string|int $companyId, string|int $employeeId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{employee_id}/letters/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Letters/List with Historical Employee Data
     *
     * Lists letters for a company. When the 'exited_employees_visibility' feature flag is enabled,
     * letters for employees who exited more than 6 weeks ago will display historical employee data
     * (forename, surname, and national_insurance_number as they were at the time of exit) instead of
     * current data.
     * This applies to the employee, recipient, and created_by associations.
     *
     * GET /companies/{company_id}/letters
     * OAuth scopes: customer
     *
     * Query parameters ($query):
     *   - include[] (mixed[])
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listCompanyLetters(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/letters', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Letters/Create
     *
     * POST /companies/{company_id}/letters
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - employee_ids (integer[]) required
     *   - letter_name (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createCompanyLetter(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/letters', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Letters/Postponement/Create
     *
     * POST /companies/{company_id}/letters/postponement
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - type (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createPostponementLetter(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/letters/postponement', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Letters/Welcome/Create
     *
     * POST /companies/{company_id}/letters/welcome
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - type (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createWelcomeLetter(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/letters/welcome', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Letters/Get
     *
     * GET /companies/{company_id}/letters/{id}
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getCompanyLetter(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/letters/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Letters/Destroy
     *
     * DELETE /companies/{company_id}/letters/{id}
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deleteCompanyLetter(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/companies/{company_id}/letters/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
