<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Mandates endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Mandates
 *
 * @see docs/smart/resources/Mandates.md
 */
class Mandates extends AbstractResource
{
    /**
     * Companies/Mandates/List
     *
     * GET /payments_service/companies/{company_uuid}/mandates
     * OAuth scopes: customer
     *
     * @param string|int $companyUuid company_uuid path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listMandates(string|int $companyUuid, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/payments_service/companies/{company_uuid}/mandates', ['company_uuid' => $companyUuid], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Mandates/Create
     *
     * POST /payments_service/companies/{company_uuid}/mandates
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - mandate (object)
     *
     * @param string|int $companyUuid company_uuid path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createMandate(string|int $companyUuid, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/payments_service/companies/{company_uuid}/mandates', ['company_uuid' => $companyUuid], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Mandates/LatestNextPossibleChargeDate
     *
     * GET /payments_service/companies/{company_uuid}/mandates/latest_next_possible_charge_date
     * OAuth scopes: customer
     *
     * @param string|int $companyUuid company_uuid path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getLatestNextPossibleChargeDate(string|int $companyUuid, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/payments_service/companies/{company_uuid}/mandates/latest_next_possible_charge_date', ['company_uuid' => $companyUuid], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Mandates/Get
     *
     * GET /payments_service/companies/{company_uuid}/mandates/{mandate_uuid}
     * OAuth scopes: customer
     *
     * @param string|int $companyUuid company_uuid path parameter
     * @param string|int $mandateUuid mandate_uuid path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getMandate(string|int $companyUuid, string|int $mandateUuid, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/payments_service/companies/{company_uuid}/mandates/{mandate_uuid}', ['company_uuid' => $companyUuid, 'mandate_uuid' => $mandateUuid], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Mandates/Destroy
     *
     * DELETE /payments_service/companies/{company_uuid}/mandates/{mandate_uuid}
     * OAuth scopes: customer
     *
     * @param string|int $companyUuid company_uuid path parameter
     * @param string|int $mandateUuid mandate_uuid path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deleteMandate(string|int $companyUuid, string|int $mandateUuid, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/payments_service/companies/{company_uuid}/mandates/{mandate_uuid}', ['company_uuid' => $companyUuid, 'mandate_uuid' => $mandateUuid], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Mandates/Complete
     *
     * POST /payments_service/companies/{company_uuid}/mandates/{mandate_uuid}/complete
     * OAuth scopes: customer
     *
     * @param string|int $companyUuid company_uuid path parameter
     * @param string|int $mandateUuid mandate_uuid path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function completeMandate(string|int $companyUuid, string|int $mandateUuid, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/payments_service/companies/{company_uuid}/mandates/{mandate_uuid}/complete', ['company_uuid' => $companyUuid, 'mandate_uuid' => $mandateUuid], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Mandates/Select
     *
     * POST /payments_service/companies/{company_uuid}/mandates/{mandate_uuid}/select
     * OAuth scopes: customer
     *
     * @param string|int $companyUuid company_uuid path parameter
     * @param string|int $mandateUuid mandate_uuid path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function selectMandate(string|int $companyUuid, string|int $mandateUuid, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/payments_service/companies/{company_uuid}/mandates/{mandate_uuid}/select', ['company_uuid' => $companyUuid, 'mandate_uuid' => $mandateUuid], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
