<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * MandateChargeSchedules endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: MandateChargeSchedule
 *
 * @see docs/smart/resources/MandateChargeSchedules.md
 */
class MandateChargeSchedules extends AbstractResource
{
    /**
     * Companies/MandateChargeSchedule/Get
     *
     * GET /companies/{company_id}/mandate_charge_schedule
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getMandateChargeSchedule(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/mandate_charge_schedule', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/MandateChargeSchedule/Create
     *
     * POST /companies/{company_id}/mandate_charge_schedule
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - day_of_month (integer) required
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createMandateChargeSchedule(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/mandate_charge_schedule', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/MandateChargeSchedule/Update
     *
     * PATCH /companies/{company_id}/mandate_charge_schedule
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - day_of_month (integer) required
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateMandateChargeSchedule(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/mandate_charge_schedule', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
