<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * MobileAppVersions endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: MobileAppVersions
 *
 * @see docs/smart/resources/MobileAppVersions.md
 */
class MobileAppVersions extends AbstractResource
{
    /**
     * MobileAppVersions/Get
     *
     * GET /mobile_app_versions/{mobile_platform}
     * Authentication: none required
     *
     * @param string|int $mobilePlatform Mobile platform (ios or android)
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getMobileAppVersion(string|int $mobilePlatform, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/mobile_app_versions/{mobile_platform}', ['mobile_platform' => $mobilePlatform], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }
}
