<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * ModellerProjections endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: ModellerProjections
 *
 * @see docs/smart/resources/ModellerProjections.md
 */
class ModellerProjections extends AbstractResource
{
    /**
     * PensionForecast/ModellerProjections/Create
     *
     * POST /pension_forecast/modeller_projection
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - date_of_birth (string) required
     *   - gender (string) required
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createModellerProjection(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/pension_forecast/modeller_projection', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
