<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * NextPayPeriodDates endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: NextPayPeriodDate
 *
 * @see docs/smart/resources/NextPayPeriodDates.md
 */
class NextPayPeriodDates extends AbstractResource
{
    /**
     * Companies/NextPayPeriodDates/List
     *
     * GET /companies/{company_id}/next_pay_period_dates
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'asc'`, `'DESC'`, `'desc'`
     *   - filter (object)
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listNextPayPeriodDates(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/next_pay_period_dates', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
