<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Notifications endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Notifications, NotificationsAccounts
 *
 * @see docs/smart/resources/Notifications.md
 */
class Notifications extends AbstractResource
{
    /**
     * Notifications/List
     *
     * GET /companies/{company_id}/notifications
     * OAuth scopes: customer
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: category
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listNotifications(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/notifications', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Notifications/Create
     *
     * POST /companies/{company_id}/notifications
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - category (string) required
     *   - email (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createNotification(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/notifications', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Notifications/Destroy
     *
     * DELETE /companies/{company_id}/notifications/{id}
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deleteNotification(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/companies/{company_id}/notifications/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Notifications/Accounts/Create
     *
     * POST /notifications/accounts
     * Authentication: none required
     *
     * Body fields ($body, JSON):
     *   - account (object)
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createAccountNotification(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/notifications/accounts', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }
}
