<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * OptInRequests endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: OptInRequest
 *
 * @see docs/smart/resources/OptInRequests.md
 */
class OptInRequests extends AbstractResource
{
    /**
     * Companies/Employees/OptInRequests/Update
     *
     * PUT /companies/{company_id}/employees/{employee_id}/opt_in_requests/{id}
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - approved (boolean)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceOptInRequest(string|int $companyId, string|int $employeeId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/employees/{employee_id}/opt_in_requests/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Employees/OptInRequests/Update
     *
     * PATCH /companies/{company_id}/employees/{employee_id}/opt_in_requests/{id}
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - approved (boolean)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateOptInRequest(string|int $companyId, string|int $employeeId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{employee_id}/opt_in_requests/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/OptInRequests/List
     *
     * GET /companies/{company_id}/opt_in_requests
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listOptInRequests(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/opt_in_requests', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
