<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * PageVisits endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: PageVisit
 *
 * @see docs/smart/resources/PageVisits.md
 */
class PageVisits extends AbstractResource
{
    /**
     * Employees/PageVisits/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/page_visits
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - page (string) required
     *   - browser (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createPageVisit(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/page_visits', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
