<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * PaidInAmounts endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: PaidInAmounts
 *
 * @see docs/smart/resources/PaidInAmounts.md
 */
class PaidInAmounts extends AbstractResource
{
    /**
     * PaidInAmounts/List
     *
     * GET /companies/{company_id}/employees/{employee_id}/paid_in_amounts
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - calculated_ons[] (date[])
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listPaidInAmounts(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/paid_in_amounts', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
