<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Passwords endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Password
 *
 * @see docs/smart/resources/Passwords.md
 */
class Passwords extends AbstractResource
{
    /**
     * Password/Create
     *
     * POST /customers/password
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - password (string) required
     *   - password_confirmation (string)
     *   - reset_password_token (string) required
     *   - invalidate_dob_confirmation (boolean)
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createCustomerPassword(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/customers/password', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Password
     *
     * POST /users/password
     * OAuth scopes: user, adviser
     *
     * Body fields ($body, JSON):
     *   - password (string) required
     *   - password_confirmation (string)
     *   - reset_password_token (string) required
     *   - invalidate_dob_confirmation (boolean)
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createUserPassword(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/users/password', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
