<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * PayrollConfigurations endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: PayrollConfiguration, Payroll configurations
 *
 * @see docs/smart/resources/PayrollConfigurations.md
 */
class PayrollConfigurations extends AbstractResource
{
    /**
     * PayrollConfigurations/List
     *
     * GET /companies/{company_id}/payroll_configurations
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listPayrollConfigurations(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/payroll_configurations', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * payroll_configurations
     *
     * POST /companies/{company_id}/payroll_configurations
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - name (string) required
     *   - salary_rate (string) required
     *   - description (string)
     *   - frequency (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createPayrollConfiguration(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/payroll_configurations', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * PayrollConfigurations/Get
     *
     * GET /companies/{company_id}/payroll_configurations/{payroll_configuration_id}
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $payrollConfigurationId payroll_configuration_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getPayrollConfiguration(string|int $companyId, string|int $payrollConfigurationId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/payroll_configurations/{payroll_configuration_id}', ['company_id' => $companyId, 'payroll_configuration_id' => $payrollConfigurationId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * payroll_configurations
     *
     * PUT /companies/{company_id}/payroll_configurations/{payroll_configuration_id}
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - frequency (string)
     *   - name (string)
     *   - salary_rate (string)
     *   - description (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $payrollConfigurationId payroll_configuration_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replacePayrollConfiguration(string|int $companyId, string|int $payrollConfigurationId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/payroll_configurations/{payroll_configuration_id}', ['company_id' => $companyId, 'payroll_configuration_id' => $payrollConfigurationId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * payroll_configurations
     *
     * PATCH /companies/{company_id}/payroll_configurations/{payroll_configuration_id}
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - frequency (string)
     *   - name (string)
     *   - salary_rate (string)
     *   - description (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $payrollConfigurationId payroll_configuration_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updatePayrollConfiguration(string|int $companyId, string|int $payrollConfigurationId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/payroll_configurations/{payroll_configuration_id}', ['company_id' => $companyId, 'payroll_configuration_id' => $payrollConfigurationId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * PayrollConfigurations/Destroy
     *
     * DELETE /companies/{company_id}/payroll_configurations/{payroll_configuration_id}
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $payrollConfigurationId payroll_configuration_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deletePayrollConfiguration(string|int $companyId, string|int $payrollConfigurationId, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/companies/{company_id}/payroll_configurations/{payroll_configuration_id}', ['company_id' => $companyId, 'payroll_configuration_id' => $payrollConfigurationId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
