<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * PayrollConfigurationDetails endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: PayrollConfigurationDetail, Payroll configuration details
 *
 * @see docs/smart/resources/PayrollConfigurationDetails.md
 */
class PayrollConfigurationDetails extends AbstractResource
{
    /**
     * PayrollConfigurationDetails/List
     *
     * GET /companies/{company_id}/payroll_configurations/{payroll_configuration_id}/payroll_configuration_details
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: pay_period_starts_on, pay_period_ends_on, cutoff_date, payday
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $payrollConfigurationId payroll_configuration_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listPayrollConfigurationDetails(string|int $companyId, string|int $payrollConfigurationId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/payroll_configurations/{payroll_configuration_id}/payroll_configuration_details', ['company_id' => $companyId, 'payroll_configuration_id' => $payrollConfigurationId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * PayrollConfigurationDetails/BatchCreate
     *
     * POST /companies/{company_id}/payroll_configurations/{payroll_configuration_id}/payroll_configuration_details/batch_create
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - initial_payroll_configuration_details (object[]) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $payrollConfigurationId payroll_configuration_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function batchCreatePayrollConfigurationDetails(string|int $companyId, string|int $payrollConfigurationId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/payroll_configurations/{payroll_configuration_id}/payroll_configuration_details/batch_create', ['company_id' => $companyId, 'payroll_configuration_id' => $payrollConfigurationId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * PayrollConfigurationDetails/Get
     *
     * GET /companies/{company_id}/payroll_configurations/{payroll_configuration_id}/payroll_configuration_details/{id}
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - include (string): Example: `payroll_configuration`
     *   - include[] (mixed[]): Items one of: `payroll_configuration`
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $payrollConfigurationId payroll_configuration_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getPayrollConfigurationDetail(string|int $companyId, string|int $payrollConfigurationId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/payroll_configurations/{payroll_configuration_id}/payroll_configuration_details/{id}', ['company_id' => $companyId, 'payroll_configuration_id' => $payrollConfigurationId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * PayrollConfigurationDetails
     *
     * PUT /companies/{company_id}/payroll_configurations/{payroll_configuration_id}/payroll_configuration_details/{id}
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - cutoff_date (string) required
     *   - payday (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $payrollConfigurationId payroll_configuration_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replacePayrollConfigurationDetail(string|int $companyId, string|int $payrollConfigurationId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/payroll_configurations/{payroll_configuration_id}/payroll_configuration_details/{id}', ['company_id' => $companyId, 'payroll_configuration_id' => $payrollConfigurationId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * PayrollConfigurationDetails
     *
     * PATCH /companies/{company_id}/payroll_configurations/{payroll_configuration_id}/payroll_configuration_details/{id}
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - cutoff_date (string) required
     *   - payday (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $payrollConfigurationId payroll_configuration_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updatePayrollConfigurationDetail(string|int $companyId, string|int $payrollConfigurationId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/payroll_configurations/{payroll_configuration_id}/payroll_configuration_details/{id}', ['company_id' => $companyId, 'payroll_configuration_id' => $payrollConfigurationId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * preview_payroll_configuration_details
     *
     * POST /companies/{company_id}/payroll_configurations/{payroll_id}/preview_payroll_configuration_details
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - initial_payroll_configuration_details (object[]) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $payrollId payroll_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function previewPayrollConfigurationDetails(string|int $companyId, string|int $payrollId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/payroll_configurations/{payroll_id}/preview_payroll_configuration_details', ['company_id' => $companyId, 'payroll_id' => $payrollId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
