<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * PensionlabConsent endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: PensionlabConsent
 *
 * @see docs/smart/resources/PensionlabConsent.md
 */
class PensionlabConsent extends AbstractResource
{
    /**
     * PensionlabConsent/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/pensionlab_consent
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getPensionlabConsent(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/pensionlab_consent', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
