<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * PensionForecast endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: PensionForecast, PensionForecastInputs
 *
 * @see docs/smart/resources/PensionForecast.md
 */
class PensionForecast extends AbstractResource
{
    /**
     * Companies/Employees/PensionForecastInputs/Create
     *
     * GET /companies/{company_id}/employees/{employee_id}/pension_forecast
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - date_of_retirement (string)
     *   - employee_amount_contribution (number)
     *   - membership_period_type (string): One of: `'active'`, `'deferred'`, `'pensioner'`, `'cancelled'`, `'no_liability'`, `'died'`
     *   - apply_vesting (boolean)
     *   - zero_out_contribution_percentages (boolean)
     *   - employee_annual_contribution_amount (number)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getPensionForecast(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/pension_forecast', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Employees/PensionForecastInputs/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/pension_forecast
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - date_of_retirement (string)
     *   - employee_amount_contribution (number)
     *   - membership_period_type (string)
     *   - apply_vesting (boolean)
     *   - zero_out_contribution_percentages (boolean)
     *   - employee_annual_contribution_amount (number)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createPensionForecast(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/pension_forecast', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Employees/PensionForecastInputs/Get
     *
     * GET /companies/{company_id}/employees/{id}/pension_forecast_inputs
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - date_of_retirement (string)
     *   - employee_amount_contribution (number)
     *   - membership_period_type (string): One of: `'active'`, `'deferred'`, `'pensioner'`, `'cancelled'`, `'no_liability'`, `'died'`
     *   - apply_vesting (boolean)
     *   - zero_out_contribution_percentages (boolean)
     *   - employee_annual_contribution_amount (number)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getPensionForecastInputs(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{id}/pension_forecast_inputs', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
