<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Profile endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: ProfileEnforcement, ProfileMigration
 *
 * @see docs/smart/resources/Profile.md
 */
class Profile extends AbstractResource
{
    /**
     * Finalise employee profile enforcement
     *
     * POST /profile/enforcement/finalise
     * OAuth scopes: employee
     *
     * Headers ($headers):
     *   - Linking-Token required: Bearer personal token from the account linking callback
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function finaliseEnforcement(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/profile/enforcement/finalise', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Start profile enforcement flow for the authenticated employee
     *
     * POST /profile/enforcement/start
     * OAuth scopes: employee
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function startEnforcement(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/profile/enforcement/start', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Get Migration Status
     *
     * GET /profile/migration/status
     * OAuth scopes: employee
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getMigrationStatus(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/profile/migration/status', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
