<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Projections endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Projection
 *
 * @see docs/smart/resources/Projections.md
 */
class Projections extends AbstractResource
{
    /**
     * Projections/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/subaccounts/{subaccount_uuid}/projections
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - projection_age (integer)
     *   - projection_amount (number)
     *   - total_amount (number)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $subaccountUuid subaccount_uuid path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createProjection(string|int $companyId, string|int $employeeId, string|int $subaccountUuid, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/subaccounts/{subaccount_uuid}/projections', ['company_id' => $companyId, 'employee_id' => $employeeId, 'subaccount_uuid' => $subaccountUuid], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
