<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Referrals endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Referrals
 *
 * @see docs/smart/resources/Referrals.md
 */
class Referrals extends AbstractResource
{
    /**
     * Customers/Referrals/Create
     *
     * POST /customers/referrals
     * OAuth scopes: customer
     *
     * Query parameters ($query):
     *   - referee_token (string)
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createReferral(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/customers/referrals', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
