<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * RegularIncomeProjections endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: RegularIncomeProjection
 *
 * @see docs/smart/resources/RegularIncomeProjections.md
 */
class RegularIncomeProjections extends AbstractResource
{
    /**
     * RegularIncomeProjection/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/regular_income_projection
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - regular_income_amount (number)
     *   - regular_income_end_age (integer)
     *   - total_amount (number)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getRegularIncomeProjection(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/regular_income_projection', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
