<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

/**
 * Resource accessors mixed into \SMART\Api\SmartClient.
 */
trait ResourceAccessors
{
    /**
     * AccountClaiming endpoints (8).
     *
     * @see docs/smart/resources/AccountClaiming.md
     */
    public function accountClaiming(): AccountClaiming
    {
        return $this->resource(AccountClaiming::class);
    }

    /**
     * AccountSubaccountsSwitchPlans endpoints (2).
     *
     * @see docs/smart/resources/AccountSubaccountsSwitchPlans.md
     */
    public function accountSubaccountsSwitchPlans(): AccountSubaccountsSwitchPlans
    {
        return $this->resource(AccountSubaccountsSwitchPlans::class);
    }

    /**
     * Accounts endpoints (2).
     *
     * @see docs/smart/resources/Accounts.md
     */
    public function accounts(): Accounts
    {
        return $this->resource(Accounts::class);
    }

    /**
     * AddMoneyForms endpoints (3).
     *
     * @see docs/smart/resources/AddMoneyForms.md
     */
    public function addMoneyForms(): AddMoneyForms
    {
        return $this->resource(AddMoneyForms::class);
    }

    /**
     * AdditionalTaxResidences endpoints (5).
     *
     * @see docs/smart/resources/AdditionalTaxResidences.md
     */
    public function additionalTaxResidences(): AdditionalTaxResidences
    {
        return $this->resource(AdditionalTaxResidences::class);
    }

    /**
     * AdviserCompanies endpoints (2).
     *
     * @see docs/smart/resources/AdviserCompanies.md
     */
    public function adviserCompanies(): AdviserCompanies
    {
        return $this->resource(AdviserCompanies::class);
    }

    /**
     * AdviserExports endpoints (1).
     *
     * @see docs/smart/resources/AdviserExports.md
     */
    public function adviserExports(): AdviserExports
    {
        return $this->resource(AdviserExports::class);
    }

    /**
     * AdviserInvitations endpoints (3).
     *
     * @see docs/smart/resources/AdviserInvitations.md
     */
    public function adviserInvitations(): AdviserInvitations
    {
        return $this->resource(AdviserInvitations::class);
    }

    /**
     * Advisers endpoints (7).
     *
     * @see docs/smart/resources/Advisers.md
     */
    public function advisers(): Advisers
    {
        return $this->resource(Advisers::class);
    }

    /**
     * Assessments endpoints (2).
     *
     * @see docs/smart/resources/Assessments.md
     */
    public function assessments(): Assessments
    {
        return $this->resource(Assessments::class);
    }

    /**
     * AvailableFunds endpoints (1).
     *
     * @see docs/smart/resources/AvailableFunds.md
     */
    public function availableFunds(): AvailableFunds
    {
        return $this->resource(AvailableFunds::class);
    }

    /**
     * AvailableGlidepaths endpoints (1).
     *
     * @see docs/smart/resources/AvailableGlidepaths.md
     */
    public function availableGlidepaths(): AvailableGlidepaths
    {
        return $this->resource(AvailableGlidepaths::class);
    }

    /**
     * AvailableWithdrawalOptions endpoints (1).
     *
     * @see docs/smart/resources/AvailableWithdrawalOptions.md
     */
    public function availableWithdrawalOptions(): AvailableWithdrawalOptions
    {
        return $this->resource(AvailableWithdrawalOptions::class);
    }

    /**
     * BankAccountDetails endpoints (13).
     *
     * @see docs/smart/resources/BankAccountDetails.md
     */
    public function bankAccountDetails(): BankAccountDetails
    {
        return $this->resource(BankAccountDetails::class);
    }

    /**
     * Batch endpoints (1).
     *
     * @see docs/smart/resources/Batch.md
     */
    public function batch(): Batch
    {
        return $this->resource(Batch::class);
    }

    /**
     * BenefitCategories endpoints (2).
     *
     * @see docs/smart/resources/BenefitCategories.md
     */
    public function benefitCategories(): BenefitCategories
    {
        return $this->resource(BenefitCategories::class);
    }

    /**
     * BenefitCheckResults endpoints (3).
     *
     * @see docs/smart/resources/BenefitCheckResults.md
     */
    public function benefitCheckResults(): BenefitCheckResults
    {
        return $this->resource(BenefitCheckResults::class);
    }

    /**
     * BenefitEvidenceTypes endpoints (1).
     *
     * @see docs/smart/resources/BenefitEvidenceTypes.md
     */
    public function benefitEvidenceTypes(): BenefitEvidenceTypes
    {
        return $this->resource(BenefitEvidenceTypes::class);
    }

    /**
     * BenefitForms endpoints (15).
     *
     * @see docs/smart/resources/BenefitForms.md
     */
    public function benefitForms(): BenefitForms
    {
        return $this->resource(BenefitForms::class);
    }

    /**
     * BenefitGroupAutoAllocatorResults endpoints (2).
     *
     * @see docs/smart/resources/BenefitGroupAutoAllocatorResults.md
     */
    public function benefitGroupAutoAllocatorResults(): BenefitGroupAutoAllocatorResults
    {
        return $this->resource(BenefitGroupAutoAllocatorResults::class);
    }

    /**
     * BenefitGroups endpoints (3).
     *
     * @see docs/smart/resources/BenefitGroups.md
     */
    public function benefitGroups(): BenefitGroups
    {
        return $this->resource(BenefitGroups::class);
    }

    /**
     * BenefitMoneyOutState endpoints (1).
     *
     * @see docs/smart/resources/BenefitMoneyOutState.md
     */
    public function benefitMoneyOutState(): BenefitMoneyOutState
    {
        return $this->resource(BenefitMoneyOutState::class);
    }

    /**
     * BenefitSchedules endpoints (4).
     *
     * @see docs/smart/resources/BenefitSchedules.md
     */
    public function benefitSchedules(): BenefitSchedules
    {
        return $this->resource(BenefitSchedules::class);
    }

    /**
     * BenefitStatements endpoints (3).
     *
     * @see docs/smart/resources/BenefitStatements.md
     */
    public function benefitStatements(): BenefitStatements
    {
        return $this->resource(BenefitStatements::class);
    }

    /**
     * Benefits endpoints (5).
     *
     * @see docs/smart/resources/Benefits.md
     */
    public function benefits(): Benefits
    {
        return $this->resource(Benefits::class);
    }

    /**
     * Cities endpoints (1).
     *
     * @see docs/smart/resources/Cities.md
     */
    public function cities(): Cities
    {
        return $this->resource(Cities::class);
    }

    /**
     * Companies endpoints (7).
     *
     * @see docs/smart/resources/Companies.md
     */
    public function companies(): Companies
    {
        return $this->resource(Companies::class);
    }

    /**
     * CompanyAdvisers endpoints (2).
     *
     * @see docs/smart/resources/CompanyAdvisers.md
     */
    public function companyAdvisers(): CompanyAdvisers
    {
        return $this->resource(CompanyAdvisers::class);
    }

    /**
     * CompanyAutomations endpoints (3).
     *
     * @see docs/smart/resources/CompanyAutomations.md
     */
    public function companyAutomations(): CompanyAutomations
    {
        return $this->resource(CompanyAutomations::class);
    }

    /**
     * CompanyBranding endpoints (4).
     *
     * @see docs/smart/resources/CompanyBranding.md
     */
    public function companyBranding(): CompanyBranding
    {
        return $this->resource(CompanyBranding::class);
    }

    /**
     * CompanyBrandingStocks endpoints (1).
     *
     * @see docs/smart/resources/CompanyBrandingStocks.md
     */
    public function companyBrandingStocks(): CompanyBrandingStocks
    {
        return $this->resource(CompanyBrandingStocks::class);
    }

    /**
     * CompanyExports endpoints (3).
     *
     * @see docs/smart/resources/CompanyExports.md
     */
    public function companyExports(): CompanyExports
    {
        return $this->resource(CompanyExports::class);
    }

    /**
     * CompanyFees endpoints (2).
     *
     * @see docs/smart/resources/CompanyFees.md
     */
    public function companyFees(): CompanyFees
    {
        return $this->resource(CompanyFees::class);
    }

    /**
     * CompanyLookups endpoints (3).
     *
     * @see docs/smart/resources/CompanyLookups.md
     */
    public function companyLookups(): CompanyLookups
    {
        return $this->resource(CompanyLookups::class);
    }

    /**
     * CompanyRules endpoints (1).
     *
     * @see docs/smart/resources/CompanyRules.md
     */
    public function companyRules(): CompanyRules
    {
        return $this->resource(CompanyRules::class);
    }

    /**
     * CompanySchemeDetails endpoints (1).
     *
     * @see docs/smart/resources/CompanySchemeDetails.md
     */
    public function companySchemeDetails(): CompanySchemeDetails
    {
        return $this->resource(CompanySchemeDetails::class);
    }

    /**
     * Constants endpoints (1).
     *
     * @see docs/smart/resources/Constants.md
     */
    public function constants(): Constants
    {
        return $this->resource(Constants::class);
    }

    /**
     * ContributionSummaries endpoints (4).
     *
     * @see docs/smart/resources/ContributionSummaries.md
     */
    public function contributionSummaries(): ContributionSummaries
    {
        return $this->resource(ContributionSummaries::class);
    }

    /**
     * Contributions endpoints (7).
     *
     * @see docs/smart/resources/Contributions.md
     */
    public function contributions(): Contributions
    {
        return $this->resource(Contributions::class);
    }

    /**
     * Countries endpoints (3).
     *
     * @see docs/smart/resources/Countries.md
     */
    public function countries(): Countries
    {
        return $this->resource(Countries::class);
    }

    /**
     * Currencies endpoints (1).
     *
     * @see docs/smart/resources/Currencies.md
     */
    public function currencies(): Currencies
    {
        return $this->resource(Currencies::class);
    }

    /**
     * CustomAppStyling endpoints (1).
     *
     * @see docs/smart/resources/CustomAppStyling.md
     */
    public function customAppStyling(): CustomAppStyling
    {
        return $this->resource(CustomAppStyling::class);
    }

    /**
     * CustomerLeads endpoints (3).
     *
     * @see docs/smart/resources/CustomerLeads.md
     */
    public function customerLeads(): CustomerLeads
    {
        return $this->resource(CustomerLeads::class);
    }

    /**
     * CustomerRoles endpoints (3).
     *
     * @see docs/smart/resources/CustomerRoles.md
     */
    public function customerRoles(): CustomerRoles
    {
        return $this->resource(CustomerRoles::class);
    }

    /**
     * Customers endpoints (8).
     *
     * @see docs/smart/resources/Customers.md
     */
    public function customers(): Customers
    {
        return $this->resource(Customers::class);
    }

    /**
     * DeclarationOfComplianceEmployeeTotals endpoints (1).
     *
     * @see docs/smart/resources/DeclarationOfComplianceEmployeeTotals.md
     */
    public function declarationOfComplianceEmployeeTotals(): DeclarationOfComplianceEmployeeTotals
    {
        return $this->resource(DeclarationOfComplianceEmployeeTotals::class);
    }

    /**
     * DiscountedValuations endpoints (1).
     *
     * @see docs/smart/resources/DiscountedValuations.md
     */
    public function discountedValuations(): DiscountedValuations
    {
        return $this->resource(DiscountedValuations::class);
    }

    /**
     * Discovery endpoints (1).
     *
     * @see docs/smart/resources/Discovery.md
     */
    public function discovery(): Discovery
    {
        return $this->resource(Discovery::class);
    }

    /**
     * Documents endpoints (1).
     *
     * @see docs/smart/resources/Documents.md
     */
    public function documents(): Documents
    {
        return $this->resource(Documents::class);
    }

    /**
     * EconomicZones endpoints (1).
     *
     * @see docs/smart/resources/EconomicZones.md
     */
    public function economicZones(): EconomicZones
    {
        return $this->resource(EconomicZones::class);
    }

    /**
     * EmployeeConfigurations endpoints (2).
     *
     * @see docs/smart/resources/EmployeeConfigurations.md
     */
    public function employeeConfigurations(): EmployeeConfigurations
    {
        return $this->resource(EmployeeConfigurations::class);
    }

    /**
     * EmployeeExternalPensions endpoints (2).
     *
     * @see docs/smart/resources/EmployeeExternalPensions.md
     */
    public function employeeExternalPensions(): EmployeeExternalPensions
    {
        return $this->resource(EmployeeExternalPensions::class);
    }

    /**
     * EmployeeFundHoldings endpoints (3).
     *
     * @see docs/smart/resources/EmployeeFundHoldings.md
     */
    public function employeeFundHoldings(): EmployeeFundHoldings
    {
        return $this->resource(EmployeeFundHoldings::class);
    }

    /**
     * EmployeeRateRecommendations endpoints (1).
     *
     * @see docs/smart/resources/EmployeeRateRecommendations.md
     */
    public function employeeRateRecommendations(): EmployeeRateRecommendations
    {
        return $this->resource(EmployeeRateRecommendations::class);
    }

    /**
     * EmployeeVerificationChecks endpoints (3).
     *
     * @see docs/smart/resources/EmployeeVerificationChecks.md
     */
    public function employeeVerificationChecks(): EmployeeVerificationChecks
    {
        return $this->resource(EmployeeVerificationChecks::class);
    }

    /**
     * Employees endpoints (20).
     *
     * @see docs/smart/resources/Employees.md
     */
    public function employees(): Employees
    {
        return $this->resource(Employees::class);
    }

    /**
     * EmploymentCategories endpoints (1).
     *
     * @see docs/smart/resources/EmploymentCategories.md
     */
    public function employmentCategories(): EmploymentCategories
    {
        return $this->resource(EmploymentCategories::class);
    }

    /**
     * EmploymentPeriods endpoints (1).
     *
     * @see docs/smart/resources/EmploymentPeriods.md
     */
    public function employmentPeriods(): EmploymentPeriods
    {
        return $this->resource(EmploymentPeriods::class);
    }

    /**
     * EnrolmentEmployees endpoints (1).
     *
     * @see docs/smart/resources/EnrolmentEmployees.md
     */
    public function enrolmentEmployees(): EnrolmentEmployees
    {
        return $this->resource(EnrolmentEmployees::class);
    }

    /**
     * Enrolments endpoints (6).
     *
     * @see docs/smart/resources/Enrolments.md
     */
    public function enrolments(): Enrolments
    {
        return $this->resource(Enrolments::class);
    }

    /**
     * Envelopes endpoints (2).
     *
     * @see docs/smart/resources/Envelopes.md
     */
    public function envelopes(): Envelopes
    {
        return $this->resource(Envelopes::class);
    }

    /**
     * EstimateBenefitValuations endpoints (1).
     *
     * @see docs/smart/resources/EstimateBenefitValuations.md
     */
    public function estimateBenefitValuations(): EstimateBenefitValuations
    {
        return $this->resource(EstimateBenefitValuations::class);
    }

    /**
     * Exports endpoints (2).
     *
     * @see docs/smart/resources/Exports.md
     */
    public function exports(): Exports
    {
        return $this->resource(Exports::class);
    }

    /**
     * ExpressionOfWish endpoints (4).
     *
     * @see docs/smart/resources/ExpressionOfWish.md
     */
    public function expressionOfWish(): ExpressionOfWish
    {
        return $this->resource(ExpressionOfWish::class);
    }

    /**
     * ExternalEmployeeDataAvailability endpoints (1).
     *
     * @see docs/smart/resources/ExternalEmployeeDataAvailability.md
     */
    public function externalEmployeeDataAvailability(): ExternalEmployeeDataAvailability
    {
        return $this->resource(ExternalEmployeeDataAvailability::class);
    }

    /**
     * FeatureFlags endpoints (1).
     *
     * @see docs/smart/resources/FeatureFlags.md
     */
    public function featureFlags(): FeatureFlags
    {
        return $this->resource(FeatureFlags::class);
    }

    /**
     * FundSplits endpoints (1).
     *
     * @see docs/smart/resources/FundSplits.md
     */
    public function fundSplits(): FundSplits
    {
        return $this->resource(FundSplits::class);
    }

    /**
     * Funds endpoints (1).
     *
     * @see docs/smart/resources/Funds.md
     */
    public function funds(): Funds
    {
        return $this->resource(Funds::class);
    }

    /**
     * Glidepaths endpoints (1).
     *
     * @see docs/smart/resources/Glidepaths.md
     */
    public function glidepaths(): Glidepaths
    {
        return $this->resource(Glidepaths::class);
    }

    /**
     * Groups endpoints (6).
     *
     * @see docs/smart/resources/Groups.md
     */
    public function groups(): Groups
    {
        return $this->resource(Groups::class);
    }

    /**
     * HistoricalContributions endpoints (2).
     *
     * @see docs/smart/resources/HistoricalContributions.md
     */
    public function historicalContributions(): HistoricalContributions
    {
        return $this->resource(HistoricalContributions::class);
    }

    /**
     * HistoricalTransferIns endpoints (2).
     *
     * @see docs/smart/resources/HistoricalTransferIns.md
     */
    public function historicalTransferIns(): HistoricalTransferIns
    {
        return $this->resource(HistoricalTransferIns::class);
    }

    /**
     * Identity endpoints (9).
     *
     * @see docs/smart/resources/Identity.md
     */
    public function identity(): Identity
    {
        return $this->resource(Identity::class);
    }

    /**
     * Imports endpoints (4).
     *
     * @see docs/smart/resources/Imports.md
     */
    public function imports(): Imports
    {
        return $this->resource(Imports::class);
    }

    /**
     * IncomeAdequacyProjections endpoints (1).
     *
     * @see docs/smart/resources/IncomeAdequacyProjections.md
     */
    public function incomeAdequacyProjections(): IncomeAdequacyProjections
    {
        return $this->resource(IncomeAdequacyProjections::class);
    }

    /**
     * Individuals endpoints (1).
     *
     * @see docs/smart/resources/Individuals.md
     */
    public function individuals(): Individuals
    {
        return $this->resource(Individuals::class);
    }

    /**
     * InvestmentsPerformance endpoints (1).
     *
     * @see docs/smart/resources/InvestmentsPerformance.md
     */
    public function investmentsPerformance(): InvestmentsPerformance
    {
        return $this->resource(InvestmentsPerformance::class);
    }

    /**
     * Jwks endpoints (1).
     *
     * @see docs/smart/resources/Jwks.md
     */
    public function jwks(): Jwks
    {
        return $this->resource(Jwks::class);
    }

    /**
     * LaterLifeProjections endpoints (1).
     *
     * @see docs/smart/resources/LaterLifeProjections.md
     */
    public function laterLifeProjections(): LaterLifeProjections
    {
        return $this->resource(LaterLifeProjections::class);
    }

    /**
     * Letters endpoints (11).
     *
     * @see docs/smart/resources/Letters.md
     */
    public function letters(): Letters
    {
        return $this->resource(Letters::class);
    }

    /**
     * MandateChargeSchedules endpoints (3).
     *
     * @see docs/smart/resources/MandateChargeSchedules.md
     */
    public function mandateChargeSchedules(): MandateChargeSchedules
    {
        return $this->resource(MandateChargeSchedules::class);
    }

    /**
     * Mandates endpoints (7).
     *
     * @see docs/smart/resources/Mandates.md
     */
    public function mandates(): Mandates
    {
        return $this->resource(Mandates::class);
    }

    /**
     * MarketingPreferences endpoints (4).
     *
     * @see docs/smart/resources/MarketingPreferences.md
     */
    public function marketingPreferences(): MarketingPreferences
    {
        return $this->resource(MarketingPreferences::class);
    }

    /**
     * MembershipFees endpoints (1).
     *
     * @see docs/smart/resources/MembershipFees.md
     */
    public function membershipFees(): MembershipFees
    {
        return $this->resource(MembershipFees::class);
    }

    /**
     * MobileAppVersions endpoints (1).
     *
     * @see docs/smart/resources/MobileAppVersions.md
     */
    public function mobileAppVersions(): MobileAppVersions
    {
        return $this->resource(MobileAppVersions::class);
    }

    /**
     * ModellerProjections endpoints (1).
     *
     * @see docs/smart/resources/ModellerProjections.md
     */
    public function modellerProjections(): ModellerProjections
    {
        return $this->resource(ModellerProjections::class);
    }

    /**
     * MoneySummaries endpoints (1).
     *
     * @see docs/smart/resources/MoneySummaries.md
     */
    public function moneySummaries(): MoneySummaries
    {
        return $this->resource(MoneySummaries::class);
    }

    /**
     * NextPayPeriodDates endpoints (1).
     *
     * @see docs/smart/resources/NextPayPeriodDates.md
     */
    public function nextPayPeriodDates(): NextPayPeriodDates
    {
        return $this->resource(NextPayPeriodDates::class);
    }

    /**
     * Notifications endpoints (4).
     *
     * @see docs/smart/resources/Notifications.md
     */
    public function notifications(): Notifications
    {
        return $this->resource(Notifications::class);
    }

    /**
     * Onboarding endpoints (5).
     *
     * @see docs/smart/resources/Onboarding.md
     */
    public function onboarding(): Onboarding
    {
        return $this->resource(Onboarding::class);
    }

    /**
     * OptInRequests endpoints (3).
     *
     * @see docs/smart/resources/OptInRequests.md
     */
    public function optInRequests(): OptInRequests
    {
        return $this->resource(OptInRequests::class);
    }

    /**
     * OverfundingThresholds endpoints (1).
     *
     * @see docs/smart/resources/OverfundingThresholds.md
     */
    public function overfundingThresholds(): OverfundingThresholds
    {
        return $this->resource(OverfundingThresholds::class);
    }

    /**
     * PageVisits endpoints (1).
     *
     * @see docs/smart/resources/PageVisits.md
     */
    public function pageVisits(): PageVisits
    {
        return $this->resource(PageVisits::class);
    }

    /**
     * PaidInAmounts endpoints (1).
     *
     * @see docs/smart/resources/PaidInAmounts.md
     */
    public function paidInAmounts(): PaidInAmounts
    {
        return $this->resource(PaidInAmounts::class);
    }

    /**
     * Passwords endpoints (2).
     *
     * @see docs/smart/resources/Passwords.md
     */
    public function passwords(): Passwords
    {
        return $this->resource(Passwords::class);
    }

    /**
     * PaymentApprovals endpoints (2).
     *
     * @see docs/smart/resources/PaymentApprovals.md
     */
    public function paymentApprovals(): PaymentApprovals
    {
        return $this->resource(PaymentApprovals::class);
    }

    /**
     * Payments endpoints (2).
     *
     * @see docs/smart/resources/Payments.md
     */
    public function payments(): Payments
    {
        return $this->resource(Payments::class);
    }

    /**
     * PayrollConfigurationDetails endpoints (6).
     *
     * @see docs/smart/resources/PayrollConfigurationDetails.md
     */
    public function payrollConfigurationDetails(): PayrollConfigurationDetails
    {
        return $this->resource(PayrollConfigurationDetails::class);
    }

    /**
     * PayrollConfigurations endpoints (6).
     *
     * @see docs/smart/resources/PayrollConfigurations.md
     */
    public function payrollConfigurations(): PayrollConfigurations
    {
        return $this->resource(PayrollConfigurations::class);
    }

    /**
     * PensionForecast endpoints (3).
     *
     * @see docs/smart/resources/PensionForecast.md
     */
    public function pensionForecast(): PensionForecast
    {
        return $this->resource(PensionForecast::class);
    }

    /**
     * PensionlabConsent endpoints (1).
     *
     * @see docs/smart/resources/PensionlabConsent.md
     */
    public function pensionlabConsent(): PensionlabConsent
    {
        return $this->resource(PensionlabConsent::class);
    }

    /**
     * Portfolios endpoints (3).
     *
     * @see docs/smart/resources/Portfolios.md
     */
    public function portfolios(): Portfolios
    {
        return $this->resource(Portfolios::class);
    }

    /**
     * Postponements endpoints (8).
     *
     * @see docs/smart/resources/Postponements.md
     */
    public function postponements(): Postponements
    {
        return $this->resource(Postponements::class);
    }

    /**
     * PreviewContributionRates endpoints (1).
     *
     * @see docs/smart/resources/PreviewContributionRates.md
     */
    public function previewContributionRates(): PreviewContributionRates
    {
        return $this->resource(PreviewContributionRates::class);
    }

    /**
     * Profile endpoints (3).
     *
     * @see docs/smart/resources/Profile.md
     */
    public function profile(): Profile
    {
        return $this->resource(Profile::class);
    }

    /**
     * Projections endpoints (1).
     *
     * @see docs/smart/resources/Projections.md
     */
    public function projections(): Projections
    {
        return $this->resource(Projections::class);
    }

    /**
     * Referrals endpoints (1).
     *
     * @see docs/smart/resources/Referrals.md
     */
    public function referrals(): Referrals
    {
        return $this->resource(Referrals::class);
    }

    /**
     * RegularIncomeProjections endpoints (1).
     *
     * @see docs/smart/resources/RegularIncomeProjections.md
     */
    public function regularIncomeProjections(): RegularIncomeProjections
    {
        return $this->resource(RegularIncomeProjections::class);
    }

    /**
     * SSIFHeadersMappings endpoints (6).
     *
     * @see docs/smart/resources/SSIFHeadersMappings.md
     */
    public function ssifHeadersMappings(): SSIFHeadersMappings
    {
        return $this->resource(SSIFHeadersMappings::class);
    }

    /**
     * SSIFImports endpoints (14).
     *
     * @see docs/smart/resources/SSIFImports.md
     */
    public function ssifImports(): SSIFImports
    {
        return $this->resource(SSIFImports::class);
    }

    /**
     * Schemes endpoints (2).
     *
     * @see docs/smart/resources/Schemes.md
     */
    public function schemes(): Schemes
    {
        return $this->resource(Schemes::class);
    }

    /**
     * SchemesAvailableCurrencies endpoints (1).
     *
     * @see docs/smart/resources/SchemesAvailableCurrencies.md
     */
    public function schemesAvailableCurrencies(): SchemesAvailableCurrencies
    {
        return $this->resource(SchemesAvailableCurrencies::class);
    }

    /**
     * StagingDates endpoints (1).
     *
     * @see docs/smart/resources/StagingDates.md
     */
    public function stagingDates(): StagingDates
    {
        return $this->resource(StagingDates::class);
    }

    /**
     * SubaccountGroupsValuations endpoints (2).
     *
     * @see docs/smart/resources/SubaccountGroupsValuations.md
     */
    public function subaccountGroupsValuations(): SubaccountGroupsValuations
    {
        return $this->resource(SubaccountGroupsValuations::class);
    }

    /**
     * Subaccounts endpoints (3).
     *
     * @see docs/smart/resources/Subaccounts.md
     */
    public function subaccounts(): Subaccounts
    {
        return $this->resource(Subaccounts::class);
    }

    /**
     * Switches endpoints (3).
     *
     * @see docs/smart/resources/Switches.md
     */
    public function switches(): Switches
    {
        return $this->resource(Switches::class);
    }

    /**
     * Tasks endpoints (2).
     *
     * @see docs/smart/resources/Tasks.md
     */
    public function tasks(): Tasks
    {
        return $this->resource(Tasks::class);
    }

    /**
     * TaxInformationChanges endpoints (1).
     *
     * @see docs/smart/resources/TaxInformationChanges.md
     */
    public function taxInformationChanges(): TaxInformationChanges
    {
        return $this->resource(TaxInformationChanges::class);
    }

    /**
     * TaxPreview endpoints (1).
     *
     * @see docs/smart/resources/TaxPreview.md
     */
    public function taxPreview(): TaxPreview
    {
        return $this->resource(TaxPreview::class);
    }

    /**
     * TaxResidence endpoints (4).
     *
     * @see docs/smart/resources/TaxResidence.md
     */
    public function taxResidence(): TaxResidence
    {
        return $this->resource(TaxResidence::class);
    }

    /**
     * ThirdPartyPaymentProviders endpoints (4).
     *
     * @see docs/smart/resources/ThirdPartyPaymentProviders.md
     */
    public function thirdPartyPaymentProviders(): ThirdPartyPaymentProviders
    {
        return $this->resource(ThirdPartyPaymentProviders::class);
    }

    /**
     * TodoItems endpoints (2).
     *
     * @see docs/smart/resources/TodoItems.md
     */
    public function todoItems(): TodoItems
    {
        return $this->resource(TodoItems::class);
    }

    /**
     * Tokens endpoints (4).
     *
     * @see docs/smart/resources/Tokens.md
     */
    public function tokens(): Tokens
    {
        return $this->resource(Tokens::class);
    }

    /**
     * TotalFundsAmcs endpoints (1).
     *
     * @see docs/smart/resources/TotalFundsAmcs.md
     */
    public function totalFundsAmcs(): TotalFundsAmcs
    {
        return $this->resource(TotalFundsAmcs::class);
    }

    /**
     * Transactions endpoints (2).
     *
     * @see docs/smart/resources/Transactions.md
     */
    public function transactions(): Transactions
    {
        return $this->resource(Transactions::class);
    }

    /**
     * TransferIns endpoints (2).
     *
     * @see docs/smart/resources/TransferIns.md
     */
    public function transferIns(): TransferIns
    {
        return $this->resource(TransferIns::class);
    }

    /**
     * TransferMoneyReviews endpoints (1).
     *
     * @see docs/smart/resources/TransferMoneyReviews.md
     */
    public function transferMoneyReviews(): TransferMoneyReviews
    {
        return $this->resource(TransferMoneyReviews::class);
    }

    /**
     * UltimateBeneficialOwnerAndConfiguration endpoints (4).
     *
     * @see docs/smart/resources/UltimateBeneficialOwnerAndConfiguration.md
     */
    public function ultimateBeneficialOwnerAndConfiguration(): UltimateBeneficialOwnerAndConfiguration
    {
        return $this->resource(UltimateBeneficialOwnerAndConfiguration::class);
    }

    /**
     * UltimateBeneficialOwners endpoints (2).
     *
     * @see docs/smart/resources/UltimateBeneficialOwners.md
     */
    public function ultimateBeneficialOwners(): UltimateBeneficialOwners
    {
        return $this->resource(UltimateBeneficialOwners::class);
    }

    /**
     * Urls endpoints (1).
     *
     * @see docs/smart/resources/Urls.md
     */
    public function urls(): Urls
    {
        return $this->resource(Urls::class);
    }

    /**
     * Users endpoints (7).
     *
     * @see docs/smart/resources/Users.md
     */
    public function users(): Users
    {
        return $this->resource(Users::class);
    }

    /**
     * Valuations endpoints (6).
     *
     * @see docs/smart/resources/Valuations.md
     */
    public function valuations(): Valuations
    {
        return $this->resource(Valuations::class);
    }

    /**
     * VerificationChecks endpoints (3).
     *
     * @see docs/smart/resources/VerificationChecks.md
     */
    public function verificationChecks(): VerificationChecks
    {
        return $this->resource(VerificationChecks::class);
    }
}
