<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Schemes endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Scheme
 *
 * @see docs/smart/resources/Schemes.md
 */
class Schemes extends AbstractResource
{
    /**
     * Schemes/Available
     *
     * GET /schemes/available
     * Authentication: none required
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listAvailableSchemes(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/schemes/available', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * Schemes/Default
     *
     * GET /schemes/default
     * Authentication: none required
     *
     * Query parameters ($query):
     *   - include (mixed)
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getDefaultScheme(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/schemes/default', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }
}
