<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * SSIFHeadersMappings endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: SSIFHeadersMappings
 *
 * @see docs/smart/resources/SSIFHeadersMappings.md
 */
class SSIFHeadersMappings extends AbstractResource
{
    /**
     * SSIFHeadersMappings/List
     *
     * GET /companies/{company_id}/ssif_headers_mappings
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listSsifHeadersMappings(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/ssif_headers_mappings', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * SSIFHeadersMappings/Create
     *
     * POST /companies/{company_id}/ssif_headers_mappings
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - name (string) required
     *   - one_time (boolean)
     *   - schema (object) required
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createSsifHeadersMapping(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/ssif_headers_mappings', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * SSIFHeadersMappings/List
     *
     * GET /companies/{company_id}/ssif_headers_mappings/{id}
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getSsifHeadersMapping(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/ssif_headers_mappings/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * SSIFHeadersMappings/Update
     *
     * PUT /companies/{company_id}/ssif_headers_mappings/{id}
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - name (string) required
     *   - one_time (boolean)
     *   - schema (object) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceSsifHeadersMapping(string|int $companyId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/ssif_headers_mappings/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * SSIFHeadersMappings/Update
     *
     * PATCH /companies/{company_id}/ssif_headers_mappings/{id}
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - name (string) required
     *   - one_time (boolean)
     *   - schema (object) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateSsifHeadersMapping(string|int $companyId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/ssif_headers_mappings/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * SSIFHeadersMappings/Destroy
     *
     * DELETE /companies/{company_id}/ssif_headers_mappings/{id}
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deleteSsifHeadersMapping(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/companies/{company_id}/ssif_headers_mappings/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
