<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * SSIFImports endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: SSIFImports, SSIF Import
 *
 * @see docs/smart/resources/SSIFImports.md
 */
class SSIFImports extends AbstractResource
{
    /**
     * SSIFImports/List
     *
     * GET /companies/{company_id}/ssif_imports
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - offset (string)
     *   - limit (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listSsifImports(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/ssif_imports', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * SSIFImports/Create
     *
     * POST /companies/{company_id}/ssif_imports
     * OAuth scopes: user, customer
     *
     * Body fields ($body, multipart/form-data):
     *   - file (file) required
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body multipart fields; files as fopen() resources or ['contents' => ..., 'filename' => ...]
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createSsifImport(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/ssif_imports', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'multipart' => $body,
        ]);
    }

    /**
     * SSIFImports/Template
     *
     * GET /companies/{company_id}/ssif_imports/template
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getTemplate(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/ssif_imports/template', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * SSIFImports/Cancel
     *
     * POST /companies/{company_id}/ssif_imports/{id}/cancel
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function cancelSsifImport(string|int $companyId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/ssif_imports/{id}/cancel', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * SSIFImports/Submit
     *
     * POST /companies/{company_id}/ssif_imports/{id}/submit
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function submitSsifImport(string|int $companyId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/ssif_imports/{id}/submit', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * SSIFImports/Get
     *
     * GET /companies/{company_id}/ssif_imports/{ssif_import_id}
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $ssifImportId ssif_import_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getSsifImport(string|int $companyId, string|int $ssifImportId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/ssif_imports/{ssif_import_id}', ['company_id' => $companyId, 'ssif_import_id' => $ssifImportId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * SSIFImports/AssignSSIFHeadersMapping
     *
     * POST /companies/{company_id}/ssif_imports/{ssif_import_id}/assign_ssif_headers_mapping
     * OAuth scopes: user, customer
     *
     * Body fields ($body, JSON):
     *   - ssif_headers_mapping_id (integer) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $ssifImportId ssif_import_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function assignHeadersMapping(string|int $companyId, string|int $ssifImportId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/ssif_imports/{ssif_import_id}/assign_ssif_headers_mapping', ['company_id' => $companyId, 'ssif_import_id' => $ssifImportId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * SSIFImports/FileHeaders
     *
     * GET /companies/{company_id}/ssif_imports/{ssif_import_id}/file_headers
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $ssifImportId ssif_import_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listFileHeaders(string|int $companyId, string|int $ssifImportId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/ssif_imports/{ssif_import_id}/file_headers', ['company_id' => $companyId, 'ssif_import_id' => $ssifImportId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * SSIFImports/Preview/Get
     *
     * GET /companies/{company_id}/ssif_imports/{ssif_import_id}/preview
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $ssifImportId ssif_import_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getPreview(string|int $companyId, string|int $ssifImportId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/ssif_imports/{ssif_import_id}/preview', ['company_id' => $companyId, 'ssif_import_id' => $ssifImportId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * SSIFImports/Preview/MissingEmployees
     *
     * GET /companies/{company_id}/ssif_imports/{ssif_import_id}/preview/ssif_import_missing_employees
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - offset (string)
     *   - limit (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $ssifImportId ssif_import_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listPreviewMissingEmployees(string|int $companyId, string|int $ssifImportId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/ssif_imports/{ssif_import_id}/preview/ssif_import_missing_employees', ['company_id' => $companyId, 'ssif_import_id' => $ssifImportId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * SSIFImports/Preview/List
     *
     * GET /companies/{company_id}/ssif_imports/{ssif_import_id}/preview/ssif_import_results
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - offset (string)
     *   - limit (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $ssifImportId ssif_import_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listPreviewResults(string|int $companyId, string|int $ssifImportId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/ssif_imports/{ssif_import_id}/preview/ssif_import_results', ['company_id' => $companyId, 'ssif_import_id' => $ssifImportId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * SSIFImports/SSIFImportMissingEmployees/List
     *
     * GET /companies/{company_id}/ssif_imports/{ssif_import_id}/ssif_import_missing_employees
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - offset (string)
     *   - limit (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $ssifImportId ssif_import_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listMissingEmployees(string|int $companyId, string|int $ssifImportId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/ssif_imports/{ssif_import_id}/ssif_import_missing_employees', ['company_id' => $companyId, 'ssif_import_id' => $ssifImportId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * SSIFImports/SSIFImportResults/List
     *
     * GET /companies/{company_id}/ssif_imports/{ssif_import_id}/ssif_import_results
     * OAuth scopes: user, customer
     *
     * Query parameters ($query):
     *   - offset (string)
     *   - limit (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $ssifImportId ssif_import_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listResults(string|int $companyId, string|int $ssifImportId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/ssif_imports/{ssif_import_id}/ssif_import_results', ['company_id' => $companyId, 'ssif_import_id' => $ssifImportId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * SSIFImport/Get
     *
     * GET /ssif_imports/download_template
     * OAuth scopes: user, customer
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function downloadTemplate(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/ssif_imports/download_template', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
