<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * StagingDates endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: StagingDate
 *
 * @see docs/smart/resources/StagingDates.md
 */
class StagingDates extends AbstractResource
{
    /**
     * StagingDate/Get
     *
     * GET /tpr/staging_date
     * Authentication: none required
     *
     * Query parameters ($query):
     *   - num (string)
     *   - ref (string)
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getStagingDate(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/tpr/staging_date', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }
}
