<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Subaccounts endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Subaccounts
 *
 * @see docs/smart/resources/Subaccounts.md
 */
class Subaccounts extends AbstractResource
{
    /**
     * Companies/Employees/Subaccounts
     *
     * GET /companies/{company_id}/employees/{employee_id}/subaccounts
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: subaccount_group, frontend_tag
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * Headers ($headers):
     *   - X-Account-Id: Account ID, provided when authenticating with profile JWT token
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listSubaccounts(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/subaccounts', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Employees/Subaccounts/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/subaccounts/{uuid}
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $uuid uuid path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getSubaccount(string|int $companyId, string|int $employeeId, string|int $uuid, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/subaccounts/{uuid}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'uuid' => $uuid], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Employees/Subaccounts/DefaultFundSplits
     *
     * GET /companies/{company_id}/employees/{employee_id}/subaccounts/{uuid}/default_fund_splits
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $uuid uuid path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getSubaccountDefaultFundSplits(string|int $companyId, string|int $employeeId, string|int $uuid, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/subaccounts/{uuid}/default_fund_splits', ['company_id' => $companyId, 'employee_id' => $employeeId, 'uuid' => $uuid], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
