<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * SubaccountGroupsValuations endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Subaccount Groups Valuations
 *
 * @see docs/smart/resources/SubaccountGroupsValuations.md
 */
class SubaccountGroupsValuations extends AbstractResource
{
    /**
     * SubaccountGroupsValuations/List
     *
     * GET /companies/{company_id}/employees/{employee_id}/subaccount_groups_valuations
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listSubaccountGroupsValuations(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/subaccount_groups_valuations', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * SubaccountGroupsValuations/List
     *
     * GET /employees/subaccount_groups_valuations
     * OAuth scopes: employee
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listMySubaccountGroupsValuations(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/employees/subaccount_groups_valuations', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
