<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Switches endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Switches
 *
 * @see docs/smart/resources/Switches.md
 */
class Switches extends AbstractResource
{
    /**
     * Companies/Employees/Switches/Delayability
     *
     * GET /companies/{company_id}/employees/{employee_id}/switches/delayability
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - subaccount_uuid (string)
     *   - subaccount_uuid (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getSwitchDelayability(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/switches/delayability', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Employees/Switches/RequestForCurrentHoldings
     *
     * POST /companies/{company_id}/employees/{employee_id}/switches/request_for_current_holdings
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - from_subaccount_uuid (string) required
     *   - to_subaccount_uuid (string) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function requestSwitchForCurrentHoldings(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/switches/request_for_current_holdings', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Employees/Switches/RequestMonetary
     *
     * POST /companies/{company_id}/employees/{employee_id}/switches/request_monetary
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - from_subaccount_uuid (string) required
     *   - to_subaccount_uuid (string) required
     *   - amount (number) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function requestMonetarySwitch(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/switches/request_monetary', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
