<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Tasks endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Tasks
 *
 * @see docs/smart/resources/Tasks.md
 */
class Tasks extends AbstractResource
{
    /**
     * Tasks/List
     *
     * GET /companies/{company_id}/employees/{employee_id}/tasks
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listEmployeeTasks(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/tasks', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Tasks/List
     *
     * GET /companies/{company_id}/tasks
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listCompanyTasks(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/tasks', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
