<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * TaxPreview endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Tax Preview
 *
 * @see docs/smart/resources/TaxPreview.md
 */
class TaxPreview extends AbstractResource
{
    /**
     * TaxPreview/Get
     *
     * GET /companies/{id}/employees/{employee_id}/benefit_categories/{benefit_rule_set_id}/tax_preview
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - amount (integer)
     *
     * @param string|int $id id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $benefitRuleSetId benefit_rule_set_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getTaxPreview(string|int $id, string|int $employeeId, string|int $benefitRuleSetId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{id}/employees/{employee_id}/benefit_categories/{benefit_rule_set_id}/tax_preview', ['id' => $id, 'employee_id' => $employeeId, 'benefit_rule_set_id' => $benefitRuleSetId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
