<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * TaxResidence endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: TaxResidence
 *
 * @see docs/smart/resources/TaxResidence.md
 */
class TaxResidence extends AbstractResource
{
    /**
     * Companies/Employees/TaxResidence/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/tax_residence
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getTaxResidence(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/tax_residence', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/Employees/TaxResidence/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/tax_residence
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - country_of_birth (string) required
     *   - us_tax_status (string) required
     *   - us_taxpayer_identification_number (string)
     *   - city_of_birth (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createTaxResidence(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/tax_residence', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Employees/TaxResidence/Update
     *
     * PUT /companies/{company_id}/employees/{employee_id}/tax_residence
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - country_of_birth (string)
     *   - us_tax_status (string)
     *   - us_taxpayer_identification_number (string)
     *   - city_of_birth (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceTaxResidence(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/employees/{employee_id}/tax_residence', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Companies/Employees/TaxResidence/Update
     *
     * PATCH /companies/{company_id}/employees/{employee_id}/tax_residence
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - country_of_birth (string)
     *   - us_tax_status (string)
     *   - us_taxpayer_identification_number (string)
     *   - city_of_birth (string)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateTaxResidence(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/employees/{employee_id}/tax_residence', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
