<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * ThirdPartyPaymentProviders endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: ThirdPartyPaymentProviders, ThirdPartyPaymentProvider
 *
 * @see docs/smart/resources/ThirdPartyPaymentProviders.md
 */
class ThirdPartyPaymentProviders extends AbstractResource
{
    /**
     * Companies/ThirdPartyPaymentProviders/List
     *
     * GET /companies/{company_id}/third_party_payment_providers
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listThirdPartyPaymentProviders(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/third_party_payment_providers', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/ThirdPartyPaymentProviders/Get
     *
     * GET /companies/{company_id}/third_party_payment_providers/{id}
     * OAuth scopes: customer
     *
     * Query parameters ($query):
     *   - include[] (mixed[]): Items one of: `directors`, `documents`
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getThirdPartyPaymentProvider(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/third_party_payment_providers/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/ThirdPartyPaymentProvider/Destroy
     *
     * DELETE /companies/{company_id}/third_party_payment_providers/{id}
     * OAuth scopes: customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deleteThirdPartyPaymentProvider(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/companies/{company_id}/third_party_payment_providers/{id}', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Companies/ThirdPartyPaymentProviders/Get
     *
     * GET /companies/{company_id}/third_party_payment_providers/{id}/sensitive_data
     * OAuth scopes: customer
     *
     * Query parameters ($query):
     *   - bank_account_detail_id (string)
     *   - field_names[] (string[]) required
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getThirdPartyPaymentProviderSensitiveData(string|int $companyId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/third_party_payment_providers/{id}/sensitive_data', ['company_id' => $companyId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
