<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Tokens endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Tokens
 *
 * @see docs/smart/resources/Tokens.md
 */
class Tokens extends AbstractResource
{
    /**
     * Tokens/Callback
     *
     * GET /employee/callbacks/smartpension
     * Authentication: none required
     *
     * Query parameters ($query):
     *   - code (string)
     *
     * Headers ($headers):
     *   - Token-Type: Type of authentication token.
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function smartPensionCallback(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/employee/callbacks/smartpension', [], [
            'query' => $query,
            'headers' => $headers,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * Tokens/Create
     *
     * Please contact our support if you are interested in connecting to our API through the external
     * application. Once they create an Partner application you will be issued with a Client ID and a
     * Client Secret. If you already are one of our partners please remember to use scope to define what
     * kind of resource JWT token will have access.
     *
     * POST /oauth/token
     * Authentication: none required
     *
     * Query parameters ($query):
     *   - token_type (string): Fallback for the Token-Type header: request a JWT by passing `jwt` when the HTTP client cannot set custom headers.
     *
     * Body fields ($body, JSON):
     *   - client_id (mixed) required
     *   - client_secret (mixed) required
     *   - username (mixed)
     *   - password (mixed)
     *   - grant_type (mixed) required
     *
     * Headers ($headers):
     *   - Token-Type: Type of authentication token.
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createToken(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/oauth/token', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
            'auth' => \SMART\Api\SmartClient::AUTH_OPTIONAL,
        ]);
    }

    /**
     * Tokens/Info
     *
     * GET /oauth/token/info
     * OAuth scopes: employee
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getTokenInfo(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/oauth/token/info', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Tokens/Refresh
     *
     * POST /refresh_token
     * OAuth scopes: employee
     *
     * Headers ($headers):
     *   - Token-Type: Type of authentication token.
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function refreshToken(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/refresh_token', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
