<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * TotalFundsAmcs endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: TotalFundsAMCs
 *
 * @see docs/smart/resources/TotalFundsAmcs.md
 */
class TotalFundsAmcs extends AbstractResource
{
    /**
     * Companies/TotalFundsAmcs/List
     *
     * GET /companies/{company_id}/total_funds_amcs
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listTotalFundsAmcs(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/total_funds_amcs', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
