<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Transactions endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Transactions
 *
 * @see docs/smart/resources/Transactions.md
 */
class Transactions extends AbstractResource
{
    /**
     * Transactions/List
     *
     * GET /companies/{company_id}/employees/{employee_id}/transactions
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - direction (string): One of: `'DESC'`, `'ASC'`
     *   - starts_on (string)
     *   - ends_on (string)
     *   - types (string[]): Items one of: `transfer_out`, `contribution`, `transfer_in`, `asset_transfer`, `adjustment`, `benefit`, `fee`, `contribution_charge`, `transfer_in_charge`, `historical_contribution`, `historical_transfer_in`, `switch`
     *   - adjustment_categories (string[]): Items one of: `payroll_error`, `adviser_error`, `employer_error`, `platform_operator_error`, `system_error`, `manual_fee`, `subaccounts_migration`
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listTransactions(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/transactions', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Transactions/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/transactions/{transaction_type}/{transaction_id}
     * OAuth scopes: employee
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $transactionType transaction_type path parameter
     * @param string|int $transactionId transaction_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getTransaction(string|int $companyId, string|int $employeeId, string|int $transactionType, string|int $transactionId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/transactions/{transaction_type}/{transaction_id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'transaction_type' => $transactionType, 'transaction_id' => $transactionId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
