<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * UltimateBeneficialOwnerAndConfiguration endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: UltimateBeneficialOwnerAndConfiguration
 *
 * @see docs/smart/resources/UltimateBeneficialOwnerAndConfiguration.md
 */
class UltimateBeneficialOwnerAndConfiguration extends AbstractResource
{
    /**
     * Companies/UltimateBeneficialOwnerAndConfigurations/Get
     *
     * GET /companies/{company_id}/ultimate_beneficial_owner_and_configuration
     * OAuth scopes: customer
     *
     * Query parameters ($query):
     *   - include[] (mixed[]): Items one of: `ultimate_beneficial_owners`
     *
     * @param string|int $companyId company_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getUltimateBeneficialOwnerAndConfiguration(string|int $companyId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/ultimate_beneficial_owner_and_configuration', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * UltimateBeneficialOwnerAndConfigurations/Create
     *
     * POST /companies/{company_id}/ultimate_beneficial_owner_and_configuration
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - exempt (boolean)
     *   - exemption_reason (string)
     *   - natural_person_ubo (boolean)
     *   - publicly_listed (boolean)
     *   - public_entity_name (string)
     *   - stock_exchange (string)
     *   - government_entity (boolean)
     *   - government_entity_name (string)
     *   - government_entity_country (string)
     *   - non_significant_control_individuals_registered (boolean)
     *   - tax_registration_number (string)
     *   - ultimate_beneficial_owners (object[])
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createUltimateBeneficialOwnerAndConfiguration(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/ultimate_beneficial_owner_and_configuration', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * UltimateBeneficialOwnerAndConfigurations/Update
     *
     * PUT /companies/{company_id}/ultimate_beneficial_owner_and_configuration
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - exempt (boolean)
     *   - exemption_reason (string)
     *   - natural_person_ubo (boolean)
     *   - publicly_listed (boolean)
     *   - public_entity_name (string)
     *   - stock_exchange (string)
     *   - government_entity (boolean)
     *   - government_entity_name (string)
     *   - government_entity_country (string)
     *   - non_significant_control_individuals_registered (boolean)
     *   - tax_registration_number (string)
     *   - ultimate_beneficial_owners (object[])
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceUltimateBeneficialOwnerAndConfiguration(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/companies/{company_id}/ultimate_beneficial_owner_and_configuration', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * UltimateBeneficialOwnerAndConfigurations/Update
     *
     * PATCH /companies/{company_id}/ultimate_beneficial_owner_and_configuration
     * OAuth scopes: customer
     *
     * Body fields ($body, JSON):
     *   - exempt (boolean)
     *   - exemption_reason (string)
     *   - natural_person_ubo (boolean)
     *   - publicly_listed (boolean)
     *   - public_entity_name (string)
     *   - stock_exchange (string)
     *   - government_entity (boolean)
     *   - government_entity_name (string)
     *   - government_entity_country (string)
     *   - non_significant_control_individuals_registered (boolean)
     *   - tax_registration_number (string)
     *   - ultimate_beneficial_owners (object[])
     *
     * @param string|int $companyId company_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateUltimateBeneficialOwnerAndConfiguration(string|int $companyId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/companies/{company_id}/ultimate_beneficial_owner_and_configuration', ['company_id' => $companyId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }
}
