<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Users endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: User
 *
 * @see docs/smart/resources/Users.md
 */
class Users extends AbstractResource
{
    /**
     * Users/List
     *
     * GET /advisers/{adviser_id}/users
     * OAuth scopes: user
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: email, forename, surname
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $adviserId adviser_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listUsers(string|int $adviserId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/advisers/{adviser_id}/users', ['adviser_id' => $adviserId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Users/Create
     *
     * POST /advisers/{adviser_id}/users
     * OAuth scopes: user
     *
     * Body fields ($body, JSON):
     *   - logo (file)
     *   - name (string) required
     *   - address (string) required
     *   - signup_start (string)
     *   - signup_finish (string)
     *   - channel (string)
     *   - agent_number (string)
     *   - broker_role (string)
     *   - broker_channel (string)
     *   - annuity_option_enabled (boolean)
     *   - marketing_included (boolean)
     *   - email (string) required
     *   - password (string) required
     *   - title (string)
     *   - forename (string) required
     *   - surname (string) required
     *   - telephone (string) required
     *
     * @param string|int $adviserId adviser_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createUser(string|int $adviserId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/advisers/{adviser_id}/users', ['adviser_id' => $adviserId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Users/Get
     *
     * GET /advisers/{adviser_id}/users/{id}
     * OAuth scopes: user
     *
     * Query parameters ($query):
     *   - include[] (mixed[]): Items one of: `adviser`, `adviser.company_tax_reliefs`
     *
     * @param string|int $adviserId adviser_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getUser(string|int $adviserId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/advisers/{adviser_id}/users/{id}', ['adviser_id' => $adviserId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Users/Update
     *
     * PUT /advisers/{adviser_id}/users/{id}
     * OAuth scopes: user
     *
     * Body fields ($body, JSON):
     *   - logo (file)
     *   - name (string)
     *   - address (string)
     *   - signup_start (string)
     *   - signup_finish (string)
     *   - channel (string)
     *   - agent_number (string)
     *   - broker_role (string)
     *   - broker_channel (string)
     *   - annuity_option_enabled (boolean)
     *
     * @param string|int $adviserId adviser_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function replaceUser(string|int $adviserId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PUT', '/advisers/{adviser_id}/users/{id}', ['adviser_id' => $adviserId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Users/Update
     *
     * PATCH /advisers/{adviser_id}/users/{id}
     * OAuth scopes: user
     *
     * Body fields ($body, JSON):
     *   - logo (file)
     *   - name (string)
     *   - address (string)
     *   - signup_start (string)
     *   - signup_finish (string)
     *   - channel (string)
     *   - agent_number (string)
     *   - broker_role (string)
     *   - broker_channel (string)
     *   - annuity_option_enabled (boolean)
     *
     * @param string|int $adviserId adviser_id path parameter
     * @param string|int $id id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function updateUser(string|int $adviserId, string|int $id, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('PATCH', '/advisers/{adviser_id}/users/{id}', ['adviser_id' => $adviserId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Users/Destroy
     *
     * DELETE /advisers/{adviser_id}/users/{id}
     * OAuth scopes: user
     *
     * @param string|int $adviserId adviser_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function deleteUser(string|int $adviserId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('DELETE', '/advisers/{adviser_id}/users/{id}', ['adviser_id' => $adviserId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Users/Session
     *
     * GET /users/session
     * OAuth scopes: user
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getUserSession(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/users/session', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
