<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * Valuations endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: Valuations
 *
 * @see docs/smart/resources/Valuations.md
 */
class Valuations extends AbstractResource
{
    /**
     * Valuations/List
     *
     * GET /companies/{company_id}/employees/{employee_id}/valuations
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: amount, calculated_on
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listValuations(string|int $companyId, string|int $employeeId, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/valuations', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Valuations/Create
     *
     * POST /companies/{company_id}/employees/{employee_id}/valuations
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - valuation (object)
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createValuation(string|int $companyId, string|int $employeeId, array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/companies/{company_id}/employees/{employee_id}/valuations', ['company_id' => $companyId, 'employee_id' => $employeeId], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Valuations/Get
     *
     * GET /companies/{company_id}/employees/{employee_id}/valuations/{id}
     * OAuth scopes: user, customer
     *
     * @param string|int $companyId company_id path parameter
     * @param string|int $employeeId employee_id path parameter
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getValuation(string|int $companyId, string|int $employeeId, string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/companies/{company_id}/employees/{employee_id}/valuations/{id}', ['company_id' => $companyId, 'employee_id' => $employeeId, 'id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Valuations/List
     *
     * GET /employees/valuations
     * OAuth scopes: employee
     *
     * Query parameters ($query):
     *   - limit (integer)
     *   - offset (integer)
     *   - sort (string)
     *   - direction (string): One of: `'ASC'`, `'DESC'`
     *   - filter (object): Keys: amount, calculated_on
     *   - operator (string): One of: `'or'`, `'and'`
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function listMyValuations(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/employees/valuations', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * Valuations/Create
     *
     * POST /employees/valuations
     * OAuth scopes: employee
     *
     * Body fields ($body, JSON):
     *   - valuation (object)
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function createMyValuation(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/employees/valuations', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * Valuations/Get
     *
     * GET /employees/valuations/{id}
     * OAuth scopes: employee
     *
     * @param string|int $id id path parameter
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getMyValuation(string|int $id, array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/employees/valuations/{id}', ['id' => $id], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
