<?php

// This file is generated by bin/generate-smart-api.php from the Keystone OpenAPI specification. Do not edit.

namespace SMART\Api\Resources;

use SMART\Response\Response;

/**
 * VerificationChecks endpoints of the Smart Pension (Keystone) API.
 *
 * API tags: VerificationChecks
 *
 * @see docs/smart/resources/VerificationChecks.md
 */
class VerificationChecks extends AbstractResource
{
    /**
     * VerificationChecks/GenerateVerificationUrl
     *
     * POST /verification_checks/generate_verification_url
     * OAuth scopes: any valid token
     *
     * Body fields ($body, JSON):
     *   - redirect_url (string) required
     *   - target (string) required
     *   - service_name (string)
     *   - verification_check_types (mixed[])
     *
     * @param array $body JSON request body
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function generateVerificationUrl(array $body = [], array $query = [], array $headers = []): Response
    {
        return $this->send('POST', '/verification_checks/generate_verification_url', [], [
            'query' => $query,
            'headers' => $headers,
            'json' => $body,
        ]);
    }

    /**
     * VerificationChecks/State
     *
     * GET /verification_checks/state
     * OAuth scopes: any valid token
     *
     * Query parameters ($query):
     *   - target (string) required: One of: `'onboarding'`, `'single_contributions'`, `'benefit_form'`
     *   - verification_check_types[] (mixed[])
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getVerificationCheckState(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/verification_checks/state', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }

    /**
     * VerificationChecks/verification_url
     *
     * GET /verification_checks/verification_url
     * OAuth scopes: any valid token
     *
     * Query parameters ($query):
     *   - target (string): One of: `'onboarding'`, `'single_contributions'`, `'benefit_form'`
     *
     * @param array $query query string parameters
     * @param array $headers extra request headers
     *
     * @throws \SMART\Api\Exceptions\ApiException
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function getVerificationUrl(array $query = [], array $headers = []): Response
    {
        return $this->send('GET', '/verification_checks/verification_url', [], [
            'query' => $query,
            'headers' => $headers,
        ]);
    }
}
