language: php

php:
  - '8.1'
  - '8.2'
  - '8.3'

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS}

script:
  - composer test
